// Code generated by ent, DO NOT EDIT.

package invoiceapplicationitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLTE(FieldID, id))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldApplicationID, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldSourceID, v))
}

// SourceReference applies equality check predicate on the "source_reference" field. It's identical to SourceReferenceEQ.
func SourceReference(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldSourceReference, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldCreatedAt, v))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNotIn(FieldApplicationID, vs...))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLTE(FieldSourceID, v))
}

// SourceReferenceEQ applies the EQ predicate on the "source_reference" field.
func SourceReferenceEQ(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldSourceReference, v))
}

// SourceReferenceNEQ applies the NEQ predicate on the "source_reference" field.
func SourceReferenceNEQ(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNEQ(FieldSourceReference, v))
}

// SourceReferenceIn applies the In predicate on the "source_reference" field.
func SourceReferenceIn(vs ...string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldIn(FieldSourceReference, vs...))
}

// SourceReferenceNotIn applies the NotIn predicate on the "source_reference" field.
func SourceReferenceNotIn(vs ...string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNotIn(FieldSourceReference, vs...))
}

// SourceReferenceGT applies the GT predicate on the "source_reference" field.
func SourceReferenceGT(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGT(FieldSourceReference, v))
}

// SourceReferenceGTE applies the GTE predicate on the "source_reference" field.
func SourceReferenceGTE(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGTE(FieldSourceReference, v))
}

// SourceReferenceLT applies the LT predicate on the "source_reference" field.
func SourceReferenceLT(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLT(FieldSourceReference, v))
}

// SourceReferenceLTE applies the LTE predicate on the "source_reference" field.
func SourceReferenceLTE(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLTE(FieldSourceReference, v))
}

// SourceReferenceContains applies the Contains predicate on the "source_reference" field.
func SourceReferenceContains(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldContains(FieldSourceReference, v))
}

// SourceReferenceHasPrefix applies the HasPrefix predicate on the "source_reference" field.
func SourceReferenceHasPrefix(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldHasPrefix(FieldSourceReference, v))
}

// SourceReferenceHasSuffix applies the HasSuffix predicate on the "source_reference" field.
func SourceReferenceHasSuffix(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldHasSuffix(FieldSourceReference, v))
}

// SourceReferenceEqualFold applies the EqualFold predicate on the "source_reference" field.
func SourceReferenceEqualFold(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEqualFold(FieldSourceReference, v))
}

// SourceReferenceContainsFold applies the ContainsFold predicate on the "source_reference" field.
func SourceReferenceContainsFold(v string) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldContainsFold(FieldSourceReference, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLTE(FieldAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.FieldLTE(FieldCreatedAt, v))
}

// HasApplication applies the HasEdge predicate on the "application" edge.
func HasApplication() predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ApplicationTable, ApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationWith applies the HasEdge predicate on the "application" edge with a given conditions (other predicates).
func HasApplicationWith(preds ...predicate.InvoiceApplication) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(func(s *sql.Selector) {
		step := newApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceApplicationItem) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceApplicationItem) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceApplicationItem) predicate.InvoiceApplicationItem {
	return predicate.InvoiceApplicationItem(sql.NotPredicates(p))
}
