// Code generated by ent, DO NOT EDIT.

package invoiceprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldUserID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldEmail, v))
}

// TaxNumber applies equality check predicate on the "tax_number" field. It's identical to TaxNumberEQ.
func TaxNumber(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldTaxNumber, v))
}

// CompanyName applies equality check predicate on the "company_name" field. It's identical to CompanyNameEQ.
func CompanyName(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldCompanyName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldUserID, vs...))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldEmail, v))
}

// TaxNumberEQ applies the EQ predicate on the "tax_number" field.
func TaxNumberEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldTaxNumber, v))
}

// TaxNumberNEQ applies the NEQ predicate on the "tax_number" field.
func TaxNumberNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldTaxNumber, v))
}

// TaxNumberIn applies the In predicate on the "tax_number" field.
func TaxNumberIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldTaxNumber, vs...))
}

// TaxNumberNotIn applies the NotIn predicate on the "tax_number" field.
func TaxNumberNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldTaxNumber, vs...))
}

// TaxNumberGT applies the GT predicate on the "tax_number" field.
func TaxNumberGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldTaxNumber, v))
}

// TaxNumberGTE applies the GTE predicate on the "tax_number" field.
func TaxNumberGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldTaxNumber, v))
}

// TaxNumberLT applies the LT predicate on the "tax_number" field.
func TaxNumberLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldTaxNumber, v))
}

// TaxNumberLTE applies the LTE predicate on the "tax_number" field.
func TaxNumberLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldTaxNumber, v))
}

// TaxNumberContains applies the Contains predicate on the "tax_number" field.
func TaxNumberContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldTaxNumber, v))
}

// TaxNumberHasPrefix applies the HasPrefix predicate on the "tax_number" field.
func TaxNumberHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldTaxNumber, v))
}

// TaxNumberHasSuffix applies the HasSuffix predicate on the "tax_number" field.
func TaxNumberHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldTaxNumber, v))
}

// TaxNumberEqualFold applies the EqualFold predicate on the "tax_number" field.
func TaxNumberEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldTaxNumber, v))
}

// TaxNumberContainsFold applies the ContainsFold predicate on the "tax_number" field.
func TaxNumberContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldTaxNumber, v))
}

// CompanyNameEQ applies the EQ predicate on the "company_name" field.
func CompanyNameEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldCompanyName, v))
}

// CompanyNameNEQ applies the NEQ predicate on the "company_name" field.
func CompanyNameNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldCompanyName, v))
}

// CompanyNameIn applies the In predicate on the "company_name" field.
func CompanyNameIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldCompanyName, vs...))
}

// CompanyNameNotIn applies the NotIn predicate on the "company_name" field.
func CompanyNameNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldCompanyName, vs...))
}

// CompanyNameGT applies the GT predicate on the "company_name" field.
func CompanyNameGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldCompanyName, v))
}

// CompanyNameGTE applies the GTE predicate on the "company_name" field.
func CompanyNameGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldCompanyName, v))
}

// CompanyNameLT applies the LT predicate on the "company_name" field.
func CompanyNameLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldCompanyName, v))
}

// CompanyNameLTE applies the LTE predicate on the "company_name" field.
func CompanyNameLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldCompanyName, v))
}

// CompanyNameContains applies the Contains predicate on the "company_name" field.
func CompanyNameContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldCompanyName, v))
}

// CompanyNameHasPrefix applies the HasPrefix predicate on the "company_name" field.
func CompanyNameHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldCompanyName, v))
}

// CompanyNameHasSuffix applies the HasSuffix predicate on the "company_name" field.
func CompanyNameHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldCompanyName, v))
}

// CompanyNameEqualFold applies the EqualFold predicate on the "company_name" field.
func CompanyNameEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldCompanyName, v))
}

// CompanyNameContainsFold applies the ContainsFold predicate on the "company_name" field.
func CompanyNameContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldCompanyName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceProfile) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceProfile) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceProfile) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.NotPredicates(p))
}
