// Code generated by ent, DO NOT EDIT.

package invoiceapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invoiceapplication type in the database.
	Label = "invoice_application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldApplicationNo holds the string denoting the application_no field in the database.
	FieldApplicationNo = "application_no"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldTaxNumber holds the string denoting the tax_number field in the database.
	FieldTaxNumber = "tax_number"
	// FieldCompanyName holds the string denoting the company_name field in the database.
	FieldCompanyName = "company_name"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRejectionReason holds the string denoting the rejection_reason field in the database.
	FieldRejectionReason = "rejection_reason"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCompletedBy holds the string denoting the completed_by field in the database.
	FieldCompletedBy = "completed_by"
	// FieldRejectedAt holds the string denoting the rejected_at field in the database.
	FieldRejectedAt = "rejected_at"
	// FieldRejectedBy holds the string denoting the rejected_by field in the database.
	FieldRejectedBy = "rejected_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeItems holds the string denoting the items edge name in mutations.
	EdgeItems = "items"
	// Table holds the table name of the invoiceapplication in the database.
	Table = "invoice_applications"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "invoice_applications"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ItemsTable is the table that holds the items relation/edge.
	ItemsTable = "invoice_application_items"
	// ItemsInverseTable is the table name for the InvoiceApplicationItem entity.
	// It exists in this package in order to avoid circular dependency with the "invoiceapplicationitem" package.
	ItemsInverseTable = "invoice_application_items"
	// ItemsColumn is the table column denoting the items relation/edge.
	ItemsColumn = "application_id"
)

// Columns holds all SQL columns for invoiceapplication fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldApplicationNo,
	FieldEmail,
	FieldTaxNumber,
	FieldCompanyName,
	FieldTotalAmount,
	FieldStatus,
	FieldRejectionReason,
	FieldCompletedAt,
	FieldCompletedBy,
	FieldRejectedAt,
	FieldRejectedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ApplicationNoValidator is a validator for the "application_no" field. It is called by the builders before save.
	ApplicationNoValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// TaxNumberValidator is a validator for the "tax_number" field. It is called by the builders before save.
	TaxNumberValidator func(string) error
	// CompanyNameValidator is a validator for the "company_name" field. It is called by the builders before save.
	CompanyNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceApplication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByApplicationNo orders the results by the application_no field.
func ByApplicationNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicationNo, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByTaxNumber orders the results by the tax_number field.
func ByTaxNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxNumber, opts...).ToFunc()
}

// ByCompanyName orders the results by the company_name field.
func ByCompanyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompanyName, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRejectionReason orders the results by the rejection_reason field.
func ByRejectionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectionReason, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCompletedBy orders the results by the completed_by field.
func ByCompletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedBy, opts...).ToFunc()
}

// ByRejectedAt orders the results by the rejected_at field.
func ByRejectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectedAt, opts...).ToFunc()
}

// ByRejectedBy orders the results by the rejected_by field.
func ByRejectedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByItemsCount orders the results by items count.
func ByItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newItemsStep(), opts...)
	}
}

// ByItems orders the results by items terms.
func ByItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
	)
}
