// Code generated by ent, DO NOT EDIT.

package invoiceapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserID, v))
}

// ApplicationNo applies equality check predicate on the "application_no" field. It's identical to ApplicationNoEQ.
func ApplicationNo(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldApplicationNo, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldEmail, v))
}

// TaxNumber applies equality check predicate on the "tax_number" field. It's identical to TaxNumberEQ.
func TaxNumber(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTaxNumber, v))
}

// CompanyName applies equality check predicate on the "company_name" field. It's identical to CompanyNameEQ.
func CompanyName(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCompanyName, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTotalAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldStatus, v))
}

// RejectionReason applies equality check predicate on the "rejection_reason" field. It's identical to RejectionReasonEQ.
func RejectionReason(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRejectionReason, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedBy applies equality check predicate on the "completed_by" field. It's identical to CompletedByEQ.
func CompletedBy(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCompletedBy, v))
}

// RejectedAt applies equality check predicate on the "rejected_at" field. It's identical to RejectedAtEQ.
func RejectedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRejectedAt, v))
}

// RejectedBy applies equality check predicate on the "rejected_by" field. It's identical to RejectedByEQ.
func RejectedBy(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRejectedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldUserID, vs...))
}

// ApplicationNoEQ applies the EQ predicate on the "application_no" field.
func ApplicationNoEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldApplicationNo, v))
}

// ApplicationNoNEQ applies the NEQ predicate on the "application_no" field.
func ApplicationNoNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldApplicationNo, v))
}

// ApplicationNoIn applies the In predicate on the "application_no" field.
func ApplicationNoIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldApplicationNo, vs...))
}

// ApplicationNoNotIn applies the NotIn predicate on the "application_no" field.
func ApplicationNoNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldApplicationNo, vs...))
}

// ApplicationNoGT applies the GT predicate on the "application_no" field.
func ApplicationNoGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldApplicationNo, v))
}

// ApplicationNoGTE applies the GTE predicate on the "application_no" field.
func ApplicationNoGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldApplicationNo, v))
}

// ApplicationNoLT applies the LT predicate on the "application_no" field.
func ApplicationNoLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldApplicationNo, v))
}

// ApplicationNoLTE applies the LTE predicate on the "application_no" field.
func ApplicationNoLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldApplicationNo, v))
}

// ApplicationNoContains applies the Contains predicate on the "application_no" field.
func ApplicationNoContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldApplicationNo, v))
}

// ApplicationNoHasPrefix applies the HasPrefix predicate on the "application_no" field.
func ApplicationNoHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldApplicationNo, v))
}

// ApplicationNoHasSuffix applies the HasSuffix predicate on the "application_no" field.
func ApplicationNoHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldApplicationNo, v))
}

// ApplicationNoEqualFold applies the EqualFold predicate on the "application_no" field.
func ApplicationNoEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldApplicationNo, v))
}

// ApplicationNoContainsFold applies the ContainsFold predicate on the "application_no" field.
func ApplicationNoContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldApplicationNo, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldEmail, v))
}

// TaxNumberEQ applies the EQ predicate on the "tax_number" field.
func TaxNumberEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTaxNumber, v))
}

// TaxNumberNEQ applies the NEQ predicate on the "tax_number" field.
func TaxNumberNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldTaxNumber, v))
}

// TaxNumberIn applies the In predicate on the "tax_number" field.
func TaxNumberIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldTaxNumber, vs...))
}

// TaxNumberNotIn applies the NotIn predicate on the "tax_number" field.
func TaxNumberNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldTaxNumber, vs...))
}

// TaxNumberGT applies the GT predicate on the "tax_number" field.
func TaxNumberGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldTaxNumber, v))
}

// TaxNumberGTE applies the GTE predicate on the "tax_number" field.
func TaxNumberGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldTaxNumber, v))
}

// TaxNumberLT applies the LT predicate on the "tax_number" field.
func TaxNumberLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldTaxNumber, v))
}

// TaxNumberLTE applies the LTE predicate on the "tax_number" field.
func TaxNumberLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldTaxNumber, v))
}

// TaxNumberContains applies the Contains predicate on the "tax_number" field.
func TaxNumberContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldTaxNumber, v))
}

// TaxNumberHasPrefix applies the HasPrefix predicate on the "tax_number" field.
func TaxNumberHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldTaxNumber, v))
}

// TaxNumberHasSuffix applies the HasSuffix predicate on the "tax_number" field.
func TaxNumberHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldTaxNumber, v))
}

// TaxNumberEqualFold applies the EqualFold predicate on the "tax_number" field.
func TaxNumberEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldTaxNumber, v))
}

// TaxNumberContainsFold applies the ContainsFold predicate on the "tax_number" field.
func TaxNumberContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldTaxNumber, v))
}

// CompanyNameEQ applies the EQ predicate on the "company_name" field.
func CompanyNameEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCompanyName, v))
}

// CompanyNameNEQ applies the NEQ predicate on the "company_name" field.
func CompanyNameNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldCompanyName, v))
}

// CompanyNameIn applies the In predicate on the "company_name" field.
func CompanyNameIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldCompanyName, vs...))
}

// CompanyNameNotIn applies the NotIn predicate on the "company_name" field.
func CompanyNameNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldCompanyName, vs...))
}

// CompanyNameGT applies the GT predicate on the "company_name" field.
func CompanyNameGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldCompanyName, v))
}

// CompanyNameGTE applies the GTE predicate on the "company_name" field.
func CompanyNameGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldCompanyName, v))
}

// CompanyNameLT applies the LT predicate on the "company_name" field.
func CompanyNameLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldCompanyName, v))
}

// CompanyNameLTE applies the LTE predicate on the "company_name" field.
func CompanyNameLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldCompanyName, v))
}

// CompanyNameContains applies the Contains predicate on the "company_name" field.
func CompanyNameContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldCompanyName, v))
}

// CompanyNameHasPrefix applies the HasPrefix predicate on the "company_name" field.
func CompanyNameHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldCompanyName, v))
}

// CompanyNameHasSuffix applies the HasSuffix predicate on the "company_name" field.
func CompanyNameHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldCompanyName, v))
}

// CompanyNameEqualFold applies the EqualFold predicate on the "company_name" field.
func CompanyNameEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldCompanyName, v))
}

// CompanyNameContainsFold applies the ContainsFold predicate on the "company_name" field.
func CompanyNameContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldCompanyName, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldTotalAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldStatus, v))
}

// RejectionReasonEQ applies the EQ predicate on the "rejection_reason" field.
func RejectionReasonEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRejectionReason, v))
}

// RejectionReasonNEQ applies the NEQ predicate on the "rejection_reason" field.
func RejectionReasonNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldRejectionReason, v))
}

// RejectionReasonIn applies the In predicate on the "rejection_reason" field.
func RejectionReasonIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldRejectionReason, vs...))
}

// RejectionReasonNotIn applies the NotIn predicate on the "rejection_reason" field.
func RejectionReasonNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldRejectionReason, vs...))
}

// RejectionReasonGT applies the GT predicate on the "rejection_reason" field.
func RejectionReasonGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldRejectionReason, v))
}

// RejectionReasonGTE applies the GTE predicate on the "rejection_reason" field.
func RejectionReasonGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldRejectionReason, v))
}

// RejectionReasonLT applies the LT predicate on the "rejection_reason" field.
func RejectionReasonLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldRejectionReason, v))
}

// RejectionReasonLTE applies the LTE predicate on the "rejection_reason" field.
func RejectionReasonLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldRejectionReason, v))
}

// RejectionReasonContains applies the Contains predicate on the "rejection_reason" field.
func RejectionReasonContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldRejectionReason, v))
}

// RejectionReasonHasPrefix applies the HasPrefix predicate on the "rejection_reason" field.
func RejectionReasonHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldRejectionReason, v))
}

// RejectionReasonHasSuffix applies the HasSuffix predicate on the "rejection_reason" field.
func RejectionReasonHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldRejectionReason, v))
}

// RejectionReasonIsNil applies the IsNil predicate on the "rejection_reason" field.
func RejectionReasonIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldRejectionReason))
}

// RejectionReasonNotNil applies the NotNil predicate on the "rejection_reason" field.
func RejectionReasonNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldRejectionReason))
}

// RejectionReasonEqualFold applies the EqualFold predicate on the "rejection_reason" field.
func RejectionReasonEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldRejectionReason, v))
}

// RejectionReasonContainsFold applies the ContainsFold predicate on the "rejection_reason" field.
func RejectionReasonContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldRejectionReason, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldCompletedAt))
}

// CompletedByEQ applies the EQ predicate on the "completed_by" field.
func CompletedByEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCompletedBy, v))
}

// CompletedByNEQ applies the NEQ predicate on the "completed_by" field.
func CompletedByNEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldCompletedBy, v))
}

// CompletedByIn applies the In predicate on the "completed_by" field.
func CompletedByIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldCompletedBy, vs...))
}

// CompletedByNotIn applies the NotIn predicate on the "completed_by" field.
func CompletedByNotIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldCompletedBy, vs...))
}

// CompletedByGT applies the GT predicate on the "completed_by" field.
func CompletedByGT(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldCompletedBy, v))
}

// CompletedByGTE applies the GTE predicate on the "completed_by" field.
func CompletedByGTE(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldCompletedBy, v))
}

// CompletedByLT applies the LT predicate on the "completed_by" field.
func CompletedByLT(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldCompletedBy, v))
}

// CompletedByLTE applies the LTE predicate on the "completed_by" field.
func CompletedByLTE(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldCompletedBy, v))
}

// CompletedByIsNil applies the IsNil predicate on the "completed_by" field.
func CompletedByIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldCompletedBy))
}

// CompletedByNotNil applies the NotNil predicate on the "completed_by" field.
func CompletedByNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldCompletedBy))
}

// RejectedAtEQ applies the EQ predicate on the "rejected_at" field.
func RejectedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRejectedAt, v))
}

// RejectedAtNEQ applies the NEQ predicate on the "rejected_at" field.
func RejectedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldRejectedAt, v))
}

// RejectedAtIn applies the In predicate on the "rejected_at" field.
func RejectedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldRejectedAt, vs...))
}

// RejectedAtNotIn applies the NotIn predicate on the "rejected_at" field.
func RejectedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldRejectedAt, vs...))
}

// RejectedAtGT applies the GT predicate on the "rejected_at" field.
func RejectedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldRejectedAt, v))
}

// RejectedAtGTE applies the GTE predicate on the "rejected_at" field.
func RejectedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldRejectedAt, v))
}

// RejectedAtLT applies the LT predicate on the "rejected_at" field.
func RejectedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldRejectedAt, v))
}

// RejectedAtLTE applies the LTE predicate on the "rejected_at" field.
func RejectedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldRejectedAt, v))
}

// RejectedAtIsNil applies the IsNil predicate on the "rejected_at" field.
func RejectedAtIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldRejectedAt))
}

// RejectedAtNotNil applies the NotNil predicate on the "rejected_at" field.
func RejectedAtNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldRejectedAt))
}

// RejectedByEQ applies the EQ predicate on the "rejected_by" field.
func RejectedByEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRejectedBy, v))
}

// RejectedByNEQ applies the NEQ predicate on the "rejected_by" field.
func RejectedByNEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldRejectedBy, v))
}

// RejectedByIn applies the In predicate on the "rejected_by" field.
func RejectedByIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldRejectedBy, vs...))
}

// RejectedByNotIn applies the NotIn predicate on the "rejected_by" field.
func RejectedByNotIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldRejectedBy, vs...))
}

// RejectedByGT applies the GT predicate on the "rejected_by" field.
func RejectedByGT(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldRejectedBy, v))
}

// RejectedByGTE applies the GTE predicate on the "rejected_by" field.
func RejectedByGTE(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldRejectedBy, v))
}

// RejectedByLT applies the LT predicate on the "rejected_by" field.
func RejectedByLT(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldRejectedBy, v))
}

// RejectedByLTE applies the LTE predicate on the "rejected_by" field.
func RejectedByLTE(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldRejectedBy, v))
}

// RejectedByIsNil applies the IsNil predicate on the "rejected_by" field.
func RejectedByIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldRejectedBy))
}

// RejectedByNotNil applies the NotNil predicate on the "rejected_by" field.
func RejectedByNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldRejectedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.InvoiceApplicationItem) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.NotPredicates(p))
}
