// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplicationUpdate is the builder for updating InvoiceApplication entities.
type InvoiceApplicationUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceApplicationMutation
}

// Where appends a list predicates to the InvoiceApplicationUpdate builder.
func (_u *InvoiceApplicationUpdate) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationUpdate) SetUserID(v int64) *InvoiceApplicationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableUserID(v *int64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetApplicationNo sets the "application_no" field.
func (_u *InvoiceApplicationUpdate) SetApplicationNo(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetApplicationNo(v)
	return _u
}

// SetNillableApplicationNo sets the "application_no" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableApplicationNo(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetApplicationNo(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceApplicationUpdate) SetEmail(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableEmail(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTaxNumber sets the "tax_number" field.
func (_u *InvoiceApplicationUpdate) SetTaxNumber(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetTaxNumber(v)
	return _u
}

// SetNillableTaxNumber sets the "tax_number" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableTaxNumber(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetTaxNumber(*v)
	}
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *InvoiceApplicationUpdate) SetCompanyName(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableCompanyName(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *InvoiceApplicationUpdate) SetTotalAmount(v float64) *InvoiceApplicationUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableTotalAmount(v *float64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *InvoiceApplicationUpdate) AddTotalAmount(v float64) *InvoiceApplicationUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceApplicationUpdate) SetStatus(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableStatus(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRejectionReason sets the "rejection_reason" field.
func (_u *InvoiceApplicationUpdate) SetRejectionReason(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetRejectionReason(v)
	return _u
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableRejectionReason(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetRejectionReason(*v)
	}
	return _u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (_u *InvoiceApplicationUpdate) ClearRejectionReason() *InvoiceApplicationUpdate {
	_u.mutation.ClearRejectionReason()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *InvoiceApplicationUpdate) SetCompletedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableCompletedAt(v *time.Time) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *InvoiceApplicationUpdate) ClearCompletedAt() *InvoiceApplicationUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetCompletedBy sets the "completed_by" field.
func (_u *InvoiceApplicationUpdate) SetCompletedBy(v int64) *InvoiceApplicationUpdate {
	_u.mutation.ResetCompletedBy()
	_u.mutation.SetCompletedBy(v)
	return _u
}

// SetNillableCompletedBy sets the "completed_by" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableCompletedBy(v *int64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetCompletedBy(*v)
	}
	return _u
}

// AddCompletedBy adds value to the "completed_by" field.
func (_u *InvoiceApplicationUpdate) AddCompletedBy(v int64) *InvoiceApplicationUpdate {
	_u.mutation.AddCompletedBy(v)
	return _u
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (_u *InvoiceApplicationUpdate) ClearCompletedBy() *InvoiceApplicationUpdate {
	_u.mutation.ClearCompletedBy()
	return _u
}

// SetRejectedAt sets the "rejected_at" field.
func (_u *InvoiceApplicationUpdate) SetRejectedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetRejectedAt(v)
	return _u
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableRejectedAt(v *time.Time) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetRejectedAt(*v)
	}
	return _u
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (_u *InvoiceApplicationUpdate) ClearRejectedAt() *InvoiceApplicationUpdate {
	_u.mutation.ClearRejectedAt()
	return _u
}

// SetRejectedBy sets the "rejected_by" field.
func (_u *InvoiceApplicationUpdate) SetRejectedBy(v int64) *InvoiceApplicationUpdate {
	_u.mutation.ResetRejectedBy()
	_u.mutation.SetRejectedBy(v)
	return _u
}

// SetNillableRejectedBy sets the "rejected_by" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableRejectedBy(v *int64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetRejectedBy(*v)
	}
	return _u
}

// AddRejectedBy adds value to the "rejected_by" field.
func (_u *InvoiceApplicationUpdate) AddRejectedBy(v int64) *InvoiceApplicationUpdate {
	_u.mutation.AddRejectedBy(v)
	return _u
}

// ClearRejectedBy clears the value of the "rejected_by" field.
func (_u *InvoiceApplicationUpdate) ClearRejectedBy() *InvoiceApplicationUpdate {
	_u.mutation.ClearRejectedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceApplicationUpdate) SetUpdatedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdate) SetUser(v *User) *InvoiceApplicationUpdate {
	return _u.SetUserID(v.ID)
}

// AddItemIDs adds the "items" edge to the InvoiceApplicationItem entity by IDs.
func (_u *InvoiceApplicationUpdate) AddItemIDs(ids ...int64) *InvoiceApplicationUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the InvoiceApplicationItem entity.
func (_u *InvoiceApplicationUpdate) AddItems(v ...*InvoiceApplicationItem) *InvoiceApplicationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_u *InvoiceApplicationUpdate) Mutation() *InvoiceApplicationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdate) ClearUser() *InvoiceApplicationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearItems clears all "items" edges to the InvoiceApplicationItem entity.
func (_u *InvoiceApplicationUpdate) ClearItems() *InvoiceApplicationUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to InvoiceApplicationItem entities by IDs.
func (_u *InvoiceApplicationUpdate) RemoveItemIDs(ids ...int64) *InvoiceApplicationUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to InvoiceApplicationItem entities.
func (_u *InvoiceApplicationUpdate) RemoveItems(v ...*InvoiceApplicationItem) *InvoiceApplicationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceApplicationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceApplicationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceApplicationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationUpdate) check() error {
	if v, ok := _u.mutation.ApplicationNo(); ok {
		if err := invoiceapplication.ApplicationNoValidator(v); err != nil {
			return &ValidationError{Name: "application_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.application_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := invoiceapplication.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNumber(); ok {
		if err := invoiceapplication.TaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.tax_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := invoiceapplication.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.company_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplication.user"`)
	}
	return nil
}

func (_u *InvoiceApplicationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplication.Table, invoiceapplication.Columns, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ApplicationNo(); ok {
		_spec.SetField(invoiceapplication.FieldApplicationNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoiceapplication.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNumber(); ok {
		_spec.SetField(invoiceapplication.FieldTaxNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(invoiceapplication.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RejectionReason(); ok {
		_spec.SetField(invoiceapplication.FieldRejectionReason, field.TypeString, value)
	}
	if _u.mutation.RejectionReasonCleared() {
		_spec.ClearField(invoiceapplication.FieldRejectionReason, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(invoiceapplication.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedBy(); ok {
		_spec.SetField(invoiceapplication.FieldCompletedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompletedBy(); ok {
		_spec.AddField(invoiceapplication.FieldCompletedBy, field.TypeInt64, value)
	}
	if _u.mutation.CompletedByCleared() {
		_spec.ClearField(invoiceapplication.FieldCompletedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RejectedAt(); ok {
		_spec.SetField(invoiceapplication.FieldRejectedAt, field.TypeTime, value)
	}
	if _u.mutation.RejectedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldRejectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RejectedBy(); ok {
		_spec.SetField(invoiceapplication.FieldRejectedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRejectedBy(); ok {
		_spec.AddField(invoiceapplication.FieldRejectedBy, field.TypeInt64, value)
	}
	if _u.mutation.RejectedByCleared() {
		_spec.ClearField(invoiceapplication.FieldRejectedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.ItemsTable,
			Columns: []string{invoiceapplication.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.ItemsTable,
			Columns: []string{invoiceapplication.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.ItemsTable,
			Columns: []string{invoiceapplication.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceApplicationUpdateOne is the builder for updating a single InvoiceApplication entity.
type InvoiceApplicationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceApplicationMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationUpdateOne) SetUserID(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableUserID(v *int64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetApplicationNo sets the "application_no" field.
func (_u *InvoiceApplicationUpdateOne) SetApplicationNo(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetApplicationNo(v)
	return _u
}

// SetNillableApplicationNo sets the "application_no" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableApplicationNo(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetApplicationNo(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceApplicationUpdateOne) SetEmail(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableEmail(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTaxNumber sets the "tax_number" field.
func (_u *InvoiceApplicationUpdateOne) SetTaxNumber(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetTaxNumber(v)
	return _u
}

// SetNillableTaxNumber sets the "tax_number" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableTaxNumber(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetTaxNumber(*v)
	}
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *InvoiceApplicationUpdateOne) SetCompanyName(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableCompanyName(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *InvoiceApplicationUpdateOne) SetTotalAmount(v float64) *InvoiceApplicationUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableTotalAmount(v *float64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *InvoiceApplicationUpdateOne) AddTotalAmount(v float64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceApplicationUpdateOne) SetStatus(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableStatus(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRejectionReason sets the "rejection_reason" field.
func (_u *InvoiceApplicationUpdateOne) SetRejectionReason(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetRejectionReason(v)
	return _u
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableRejectionReason(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetRejectionReason(*v)
	}
	return _u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (_u *InvoiceApplicationUpdateOne) ClearRejectionReason() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearRejectionReason()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *InvoiceApplicationUpdateOne) SetCompletedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableCompletedAt(v *time.Time) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *InvoiceApplicationUpdateOne) ClearCompletedAt() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetCompletedBy sets the "completed_by" field.
func (_u *InvoiceApplicationUpdateOne) SetCompletedBy(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.ResetCompletedBy()
	_u.mutation.SetCompletedBy(v)
	return _u
}

// SetNillableCompletedBy sets the "completed_by" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableCompletedBy(v *int64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetCompletedBy(*v)
	}
	return _u
}

// AddCompletedBy adds value to the "completed_by" field.
func (_u *InvoiceApplicationUpdateOne) AddCompletedBy(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddCompletedBy(v)
	return _u
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (_u *InvoiceApplicationUpdateOne) ClearCompletedBy() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearCompletedBy()
	return _u
}

// SetRejectedAt sets the "rejected_at" field.
func (_u *InvoiceApplicationUpdateOne) SetRejectedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetRejectedAt(v)
	return _u
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableRejectedAt(v *time.Time) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetRejectedAt(*v)
	}
	return _u
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (_u *InvoiceApplicationUpdateOne) ClearRejectedAt() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearRejectedAt()
	return _u
}

// SetRejectedBy sets the "rejected_by" field.
func (_u *InvoiceApplicationUpdateOne) SetRejectedBy(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.ResetRejectedBy()
	_u.mutation.SetRejectedBy(v)
	return _u
}

// SetNillableRejectedBy sets the "rejected_by" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableRejectedBy(v *int64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetRejectedBy(*v)
	}
	return _u
}

// AddRejectedBy adds value to the "rejected_by" field.
func (_u *InvoiceApplicationUpdateOne) AddRejectedBy(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddRejectedBy(v)
	return _u
}

// ClearRejectedBy clears the value of the "rejected_by" field.
func (_u *InvoiceApplicationUpdateOne) ClearRejectedBy() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearRejectedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceApplicationUpdateOne) SetUpdatedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdateOne) SetUser(v *User) *InvoiceApplicationUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddItemIDs adds the "items" edge to the InvoiceApplicationItem entity by IDs.
func (_u *InvoiceApplicationUpdateOne) AddItemIDs(ids ...int64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the InvoiceApplicationItem entity.
func (_u *InvoiceApplicationUpdateOne) AddItems(v ...*InvoiceApplicationItem) *InvoiceApplicationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_u *InvoiceApplicationUpdateOne) Mutation() *InvoiceApplicationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdateOne) ClearUser() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearItems clears all "items" edges to the InvoiceApplicationItem entity.
func (_u *InvoiceApplicationUpdateOne) ClearItems() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to InvoiceApplicationItem entities by IDs.
func (_u *InvoiceApplicationUpdateOne) RemoveItemIDs(ids ...int64) *InvoiceApplicationUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to InvoiceApplicationItem entities.
func (_u *InvoiceApplicationUpdateOne) RemoveItems(v ...*InvoiceApplicationItem) *InvoiceApplicationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the InvoiceApplicationUpdate builder.
func (_u *InvoiceApplicationUpdateOne) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceApplicationUpdateOne) Select(field string, fields ...string) *InvoiceApplicationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceApplication entity.
func (_u *InvoiceApplicationUpdateOne) Save(ctx context.Context) (*InvoiceApplication, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationUpdateOne) SaveX(ctx context.Context) *InvoiceApplication {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceApplicationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationUpdateOne) check() error {
	if v, ok := _u.mutation.ApplicationNo(); ok {
		if err := invoiceapplication.ApplicationNoValidator(v); err != nil {
			return &ValidationError{Name: "application_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.application_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := invoiceapplication.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNumber(); ok {
		if err := invoiceapplication.TaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.tax_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := invoiceapplication.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.company_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplication.user"`)
	}
	return nil
}

func (_u *InvoiceApplicationUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceApplication, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplication.Table, invoiceapplication.Columns, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceApplication.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceapplication.FieldID)
		for _, f := range fields {
			if !invoiceapplication.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ApplicationNo(); ok {
		_spec.SetField(invoiceapplication.FieldApplicationNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoiceapplication.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNumber(); ok {
		_spec.SetField(invoiceapplication.FieldTaxNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(invoiceapplication.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RejectionReason(); ok {
		_spec.SetField(invoiceapplication.FieldRejectionReason, field.TypeString, value)
	}
	if _u.mutation.RejectionReasonCleared() {
		_spec.ClearField(invoiceapplication.FieldRejectionReason, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(invoiceapplication.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedBy(); ok {
		_spec.SetField(invoiceapplication.FieldCompletedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompletedBy(); ok {
		_spec.AddField(invoiceapplication.FieldCompletedBy, field.TypeInt64, value)
	}
	if _u.mutation.CompletedByCleared() {
		_spec.ClearField(invoiceapplication.FieldCompletedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RejectedAt(); ok {
		_spec.SetField(invoiceapplication.FieldRejectedAt, field.TypeTime, value)
	}
	if _u.mutation.RejectedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldRejectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RejectedBy(); ok {
		_spec.SetField(invoiceapplication.FieldRejectedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRejectedBy(); ok {
		_spec.AddField(invoiceapplication.FieldRejectedBy, field.TypeInt64, value)
	}
	if _u.mutation.RejectedByCleared() {
		_spec.ClearField(invoiceapplication.FieldRejectedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.ItemsTable,
			Columns: []string{invoiceapplication.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.ItemsTable,
			Columns: []string{invoiceapplication.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.ItemsTable,
			Columns: []string{invoiceapplication.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceApplication{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
