// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceprofile"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceProfileUpdate is the builder for updating InvoiceProfile entities.
type InvoiceProfileUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceProfileMutation
}

// Where appends a list predicates to the InvoiceProfileUpdate builder.
func (_u *InvoiceProfileUpdate) Where(ps ...predicate.InvoiceProfile) *InvoiceProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceProfileUpdate) SetUserID(v int64) *InvoiceProfileUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableUserID(v *int64) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceProfileUpdate) SetEmail(v string) *InvoiceProfileUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableEmail(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTaxNumber sets the "tax_number" field.
func (_u *InvoiceProfileUpdate) SetTaxNumber(v string) *InvoiceProfileUpdate {
	_u.mutation.SetTaxNumber(v)
	return _u
}

// SetNillableTaxNumber sets the "tax_number" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableTaxNumber(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetTaxNumber(*v)
	}
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *InvoiceProfileUpdate) SetCompanyName(v string) *InvoiceProfileUpdate {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableCompanyName(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceProfileUpdate) SetUpdatedAt(v time.Time) *InvoiceProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceProfileUpdate) SetUser(v *User) *InvoiceProfileUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceProfileMutation object of the builder.
func (_u *InvoiceProfileUpdate) Mutation() *InvoiceProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceProfileUpdate) ClearUser() *InvoiceProfileUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceProfileUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := invoiceprofile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNumber(); ok {
		if err := invoiceprofile.TaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.tax_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := invoiceprofile.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.company_name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceProfile.user"`)
	}
	return nil
}

func (_u *InvoiceProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceprofile.Table, invoiceprofile.Columns, sqlgraph.NewFieldSpec(invoiceprofile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoiceprofile.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNumber(); ok {
		_spec.SetField(invoiceprofile.FieldTaxNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(invoiceprofile.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invoiceprofile.UserTable,
			Columns: []string{invoiceprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invoiceprofile.UserTable,
			Columns: []string{invoiceprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceProfileUpdateOne is the builder for updating a single InvoiceProfile entity.
type InvoiceProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceProfileMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceProfileUpdateOne) SetUserID(v int64) *InvoiceProfileUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableUserID(v *int64) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceProfileUpdateOne) SetEmail(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableEmail(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTaxNumber sets the "tax_number" field.
func (_u *InvoiceProfileUpdateOne) SetTaxNumber(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetTaxNumber(v)
	return _u
}

// SetNillableTaxNumber sets the "tax_number" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableTaxNumber(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetTaxNumber(*v)
	}
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *InvoiceProfileUpdateOne) SetCompanyName(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableCompanyName(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceProfileUpdateOne) SetUpdatedAt(v time.Time) *InvoiceProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceProfileUpdateOne) SetUser(v *User) *InvoiceProfileUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceProfileMutation object of the builder.
func (_u *InvoiceProfileUpdateOne) Mutation() *InvoiceProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceProfileUpdateOne) ClearUser() *InvoiceProfileUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the InvoiceProfileUpdate builder.
func (_u *InvoiceProfileUpdateOne) Where(ps ...predicate.InvoiceProfile) *InvoiceProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceProfileUpdateOne) Select(field string, fields ...string) *InvoiceProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceProfile entity.
func (_u *InvoiceProfileUpdateOne) Save(ctx context.Context) (*InvoiceProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceProfileUpdateOne) SaveX(ctx context.Context) *InvoiceProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := invoiceprofile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNumber(); ok {
		if err := invoiceprofile.TaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.tax_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := invoiceprofile.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.company_name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceProfile.user"`)
	}
	return nil
}

func (_u *InvoiceProfileUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceprofile.Table, invoiceprofile.Columns, sqlgraph.NewFieldSpec(invoiceprofile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceprofile.FieldID)
		for _, f := range fields {
			if !invoiceprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoiceprofile.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNumber(); ok {
		_spec.SetField(invoiceprofile.FieldTaxNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(invoiceprofile.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invoiceprofile.UserTable,
			Columns: []string{invoiceprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invoiceprofile.UserTable,
			Columns: []string{invoiceprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
