// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationitem"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplicationCreate is the builder for creating a InvoiceApplication entity.
type InvoiceApplicationCreate struct {
	config
	mutation *InvoiceApplicationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceApplicationCreate) SetUserID(v int64) *InvoiceApplicationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetApplicationNo sets the "application_no" field.
func (_c *InvoiceApplicationCreate) SetApplicationNo(v string) *InvoiceApplicationCreate {
	_c.mutation.SetApplicationNo(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *InvoiceApplicationCreate) SetEmail(v string) *InvoiceApplicationCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetTaxNumber sets the "tax_number" field.
func (_c *InvoiceApplicationCreate) SetTaxNumber(v string) *InvoiceApplicationCreate {
	_c.mutation.SetTaxNumber(v)
	return _c
}

// SetCompanyName sets the "company_name" field.
func (_c *InvoiceApplicationCreate) SetCompanyName(v string) *InvoiceApplicationCreate {
	_c.mutation.SetCompanyName(v)
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *InvoiceApplicationCreate) SetTotalAmount(v float64) *InvoiceApplicationCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceApplicationCreate) SetStatus(v string) *InvoiceApplicationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableStatus(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRejectionReason sets the "rejection_reason" field.
func (_c *InvoiceApplicationCreate) SetRejectionReason(v string) *InvoiceApplicationCreate {
	_c.mutation.SetRejectionReason(v)
	return _c
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableRejectionReason(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetRejectionReason(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *InvoiceApplicationCreate) SetCompletedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableCompletedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCompletedBy sets the "completed_by" field.
func (_c *InvoiceApplicationCreate) SetCompletedBy(v int64) *InvoiceApplicationCreate {
	_c.mutation.SetCompletedBy(v)
	return _c
}

// SetNillableCompletedBy sets the "completed_by" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableCompletedBy(v *int64) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetCompletedBy(*v)
	}
	return _c
}

// SetRejectedAt sets the "rejected_at" field.
func (_c *InvoiceApplicationCreate) SetRejectedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetRejectedAt(v)
	return _c
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableRejectedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetRejectedAt(*v)
	}
	return _c
}

// SetRejectedBy sets the "rejected_by" field.
func (_c *InvoiceApplicationCreate) SetRejectedBy(v int64) *InvoiceApplicationCreate {
	_c.mutation.SetRejectedBy(v)
	return _c
}

// SetNillableRejectedBy sets the "rejected_by" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableRejectedBy(v *int64) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetRejectedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceApplicationCreate) SetCreatedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableCreatedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceApplicationCreate) SetUpdatedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *InvoiceApplicationCreate) SetUser(v *User) *InvoiceApplicationCreate {
	return _c.SetUserID(v.ID)
}

// AddItemIDs adds the "items" edge to the InvoiceApplicationItem entity by IDs.
func (_c *InvoiceApplicationCreate) AddItemIDs(ids ...int64) *InvoiceApplicationCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the InvoiceApplicationItem entity.
func (_c *InvoiceApplicationCreate) AddItems(v ...*InvoiceApplicationItem) *InvoiceApplicationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_c *InvoiceApplicationCreate) Mutation() *InvoiceApplicationMutation {
	return _c.mutation
}

// Save creates the InvoiceApplication in the database.
func (_c *InvoiceApplicationCreate) Save(ctx context.Context) (*InvoiceApplication, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceApplicationCreate) SaveX(ctx context.Context) *InvoiceApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceApplicationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := invoiceapplication.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoiceapplication.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceApplicationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceApplication.user_id"`)}
	}
	if _, ok := _c.mutation.ApplicationNo(); !ok {
		return &ValidationError{Name: "application_no", err: errors.New(`ent: missing required field "InvoiceApplication.application_no"`)}
	}
	if v, ok := _c.mutation.ApplicationNo(); ok {
		if err := invoiceapplication.ApplicationNoValidator(v); err != nil {
			return &ValidationError{Name: "application_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.application_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "InvoiceApplication.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := invoiceapplication.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxNumber(); !ok {
		return &ValidationError{Name: "tax_number", err: errors.New(`ent: missing required field "InvoiceApplication.tax_number"`)}
	}
	if v, ok := _c.mutation.TaxNumber(); ok {
		if err := invoiceapplication.TaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.tax_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CompanyName(); !ok {
		return &ValidationError{Name: "company_name", err: errors.New(`ent: missing required field "InvoiceApplication.company_name"`)}
	}
	if v, ok := _c.mutation.CompanyName(); ok {
		if err := invoiceapplication.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.company_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "InvoiceApplication.total_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceApplication.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceApplication.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceApplication.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InvoiceApplication.user"`)}
	}
	return nil
}

func (_c *InvoiceApplicationCreate) sqlSave(ctx context.Context) (*InvoiceApplication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceApplicationCreate) createSpec() (*InvoiceApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceApplication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoiceapplication.Table, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ApplicationNo(); ok {
		_spec.SetField(invoiceapplication.FieldApplicationNo, field.TypeString, value)
		_node.ApplicationNo = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(invoiceapplication.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.TaxNumber(); ok {
		_spec.SetField(invoiceapplication.FieldTaxNumber, field.TypeString, value)
		_node.TaxNumber = value
	}
	if value, ok := _c.mutation.CompanyName(); ok {
		_spec.SetField(invoiceapplication.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RejectionReason(); ok {
		_spec.SetField(invoiceapplication.FieldRejectionReason, field.TypeString, value)
		_node.RejectionReason = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(invoiceapplication.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CompletedBy(); ok {
		_spec.SetField(invoiceapplication.FieldCompletedBy, field.TypeInt64, value)
		_node.CompletedBy = &value
	}
	if value, ok := _c.mutation.RejectedAt(); ok {
		_spec.SetField(invoiceapplication.FieldRejectedAt, field.TypeTime, value)
		_node.RejectedAt = &value
	}
	if value, ok := _c.mutation.RejectedBy(); ok {
		_spec.SetField(invoiceapplication.FieldRejectedBy, field.TypeInt64, value)
		_node.RejectedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.ItemsTable,
			Columns: []string{invoiceapplication.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplication.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationUpsertOne {
	_c.conflict = opts
	return &InvoiceApplicationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationCreate) OnConflictColumns(columns ...string) *InvoiceApplicationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceApplicationUpsertOne is the builder for "upsert"-ing
	//  one InvoiceApplication node.
	InvoiceApplicationUpsertOne struct {
		create *InvoiceApplicationCreate
	}

	// InvoiceApplicationUpsert is the "OnConflict" setter.
	InvoiceApplicationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsert) SetUserID(v int64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateUserID() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldUserID)
	return u
}

// SetApplicationNo sets the "application_no" field.
func (u *InvoiceApplicationUpsert) SetApplicationNo(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldApplicationNo, v)
	return u
}

// UpdateApplicationNo sets the "application_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateApplicationNo() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldApplicationNo)
	return u
}

// SetEmail sets the "email" field.
func (u *InvoiceApplicationUpsert) SetEmail(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateEmail() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldEmail)
	return u
}

// SetTaxNumber sets the "tax_number" field.
func (u *InvoiceApplicationUpsert) SetTaxNumber(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldTaxNumber, v)
	return u
}

// UpdateTaxNumber sets the "tax_number" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateTaxNumber() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldTaxNumber)
	return u
}

// SetCompanyName sets the "company_name" field.
func (u *InvoiceApplicationUpsert) SetCompanyName(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldCompanyName, v)
	return u
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateCompanyName() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldCompanyName)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceApplicationUpsert) SetTotalAmount(v float64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateTotalAmount() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceApplicationUpsert) AddTotalAmount(v float64) *InvoiceApplicationUpsert {
	u.Add(invoiceapplication.FieldTotalAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsert) SetStatus(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateStatus() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldStatus)
	return u
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *InvoiceApplicationUpsert) SetRejectionReason(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldRejectionReason, v)
	return u
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateRejectionReason() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldRejectionReason)
	return u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *InvoiceApplicationUpsert) ClearRejectionReason() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldRejectionReason)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *InvoiceApplicationUpsert) SetCompletedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateCompletedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *InvoiceApplicationUpsert) ClearCompletedAt() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldCompletedAt)
	return u
}

// SetCompletedBy sets the "completed_by" field.
func (u *InvoiceApplicationUpsert) SetCompletedBy(v int64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldCompletedBy, v)
	return u
}

// UpdateCompletedBy sets the "completed_by" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateCompletedBy() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldCompletedBy)
	return u
}

// AddCompletedBy adds v to the "completed_by" field.
func (u *InvoiceApplicationUpsert) AddCompletedBy(v int64) *InvoiceApplicationUpsert {
	u.Add(invoiceapplication.FieldCompletedBy, v)
	return u
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (u *InvoiceApplicationUpsert) ClearCompletedBy() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldCompletedBy)
	return u
}

// SetRejectedAt sets the "rejected_at" field.
func (u *InvoiceApplicationUpsert) SetRejectedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldRejectedAt, v)
	return u
}

// UpdateRejectedAt sets the "rejected_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateRejectedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldRejectedAt)
	return u
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (u *InvoiceApplicationUpsert) ClearRejectedAt() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldRejectedAt)
	return u
}

// SetRejectedBy sets the "rejected_by" field.
func (u *InvoiceApplicationUpsert) SetRejectedBy(v int64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldRejectedBy, v)
	return u
}

// UpdateRejectedBy sets the "rejected_by" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateRejectedBy() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldRejectedBy)
	return u
}

// AddRejectedBy adds v to the "rejected_by" field.
func (u *InvoiceApplicationUpsert) AddRejectedBy(v int64) *InvoiceApplicationUpsert {
	u.Add(invoiceapplication.FieldRejectedBy, v)
	return u
}

// ClearRejectedBy clears the value of the "rejected_by" field.
func (u *InvoiceApplicationUpsert) ClearRejectedBy() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldRejectedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsert) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateUpdatedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertOne) UpdateNewValues() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoiceapplication.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceApplicationUpsertOne) Ignore() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationUpsertOne) DoNothing() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationCreate.OnConflict
// documentation for more info.
func (u *InvoiceApplicationUpsertOne) Update(set func(*InvoiceApplicationUpsert)) *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsertOne) SetUserID(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateUserID() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserID()
	})
}

// SetApplicationNo sets the "application_no" field.
func (u *InvoiceApplicationUpsertOne) SetApplicationNo(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetApplicationNo(v)
	})
}

// UpdateApplicationNo sets the "application_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateApplicationNo() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateApplicationNo()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceApplicationUpsertOne) SetEmail(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateEmail() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateEmail()
	})
}

// SetTaxNumber sets the "tax_number" field.
func (u *InvoiceApplicationUpsertOne) SetTaxNumber(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTaxNumber(v)
	})
}

// UpdateTaxNumber sets the "tax_number" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateTaxNumber() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTaxNumber()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *InvoiceApplicationUpsertOne) SetCompanyName(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateCompanyName() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateCompanyName()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceApplicationUpsertOne) SetTotalAmount(v float64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceApplicationUpsertOne) AddTotalAmount(v float64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateTotalAmount() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsertOne) SetStatus(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateStatus() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateStatus()
	})
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *InvoiceApplicationUpsertOne) SetRejectionReason(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRejectionReason(v)
	})
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateRejectionReason() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRejectionReason()
	})
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *InvoiceApplicationUpsertOne) ClearRejectionReason() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRejectionReason()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *InvoiceApplicationUpsertOne) SetCompletedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateCompletedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *InvoiceApplicationUpsertOne) ClearCompletedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearCompletedAt()
	})
}

// SetCompletedBy sets the "completed_by" field.
func (u *InvoiceApplicationUpsertOne) SetCompletedBy(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetCompletedBy(v)
	})
}

// AddCompletedBy adds v to the "completed_by" field.
func (u *InvoiceApplicationUpsertOne) AddCompletedBy(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddCompletedBy(v)
	})
}

// UpdateCompletedBy sets the "completed_by" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateCompletedBy() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateCompletedBy()
	})
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (u *InvoiceApplicationUpsertOne) ClearCompletedBy() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearCompletedBy()
	})
}

// SetRejectedAt sets the "rejected_at" field.
func (u *InvoiceApplicationUpsertOne) SetRejectedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRejectedAt(v)
	})
}

// UpdateRejectedAt sets the "rejected_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateRejectedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRejectedAt()
	})
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (u *InvoiceApplicationUpsertOne) ClearRejectedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRejectedAt()
	})
}

// SetRejectedBy sets the "rejected_by" field.
func (u *InvoiceApplicationUpsertOne) SetRejectedBy(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRejectedBy(v)
	})
}

// AddRejectedBy adds v to the "rejected_by" field.
func (u *InvoiceApplicationUpsertOne) AddRejectedBy(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddRejectedBy(v)
	})
}

// UpdateRejectedBy sets the "rejected_by" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateRejectedBy() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRejectedBy()
	})
}

// ClearRejectedBy clears the value of the "rejected_by" field.
func (u *InvoiceApplicationUpsertOne) ClearRejectedBy() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRejectedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsertOne) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateUpdatedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceApplicationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceApplicationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceApplicationCreateBulk is the builder for creating many InvoiceApplication entities in bulk.
type InvoiceApplicationCreateBulk struct {
	config
	err      error
	builders []*InvoiceApplicationCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceApplication entities in the database.
func (_c *InvoiceApplicationCreateBulk) Save(ctx context.Context) ([]*InvoiceApplication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceApplication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceApplicationCreateBulk) SaveX(ctx context.Context) []*InvoiceApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplication.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationUpsertBulk {
	_c.conflict = opts
	return &InvoiceApplicationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationCreateBulk) OnConflictColumns(columns ...string) *InvoiceApplicationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationUpsertBulk{
		create: _c,
	}
}

// InvoiceApplicationUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceApplication nodes.
type InvoiceApplicationUpsertBulk struct {
	create *InvoiceApplicationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertBulk) UpdateNewValues() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoiceapplication.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertBulk) Ignore() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationUpsertBulk) DoNothing() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceApplicationUpsertBulk) Update(set func(*InvoiceApplicationUpsert)) *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsertBulk) SetUserID(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateUserID() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserID()
	})
}

// SetApplicationNo sets the "application_no" field.
func (u *InvoiceApplicationUpsertBulk) SetApplicationNo(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetApplicationNo(v)
	})
}

// UpdateApplicationNo sets the "application_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateApplicationNo() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateApplicationNo()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceApplicationUpsertBulk) SetEmail(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateEmail() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateEmail()
	})
}

// SetTaxNumber sets the "tax_number" field.
func (u *InvoiceApplicationUpsertBulk) SetTaxNumber(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTaxNumber(v)
	})
}

// UpdateTaxNumber sets the "tax_number" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateTaxNumber() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTaxNumber()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *InvoiceApplicationUpsertBulk) SetCompanyName(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateCompanyName() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateCompanyName()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceApplicationUpsertBulk) SetTotalAmount(v float64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceApplicationUpsertBulk) AddTotalAmount(v float64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateTotalAmount() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsertBulk) SetStatus(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateStatus() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateStatus()
	})
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *InvoiceApplicationUpsertBulk) SetRejectionReason(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRejectionReason(v)
	})
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateRejectionReason() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRejectionReason()
	})
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *InvoiceApplicationUpsertBulk) ClearRejectionReason() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRejectionReason()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *InvoiceApplicationUpsertBulk) SetCompletedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateCompletedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *InvoiceApplicationUpsertBulk) ClearCompletedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearCompletedAt()
	})
}

// SetCompletedBy sets the "completed_by" field.
func (u *InvoiceApplicationUpsertBulk) SetCompletedBy(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetCompletedBy(v)
	})
}

// AddCompletedBy adds v to the "completed_by" field.
func (u *InvoiceApplicationUpsertBulk) AddCompletedBy(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddCompletedBy(v)
	})
}

// UpdateCompletedBy sets the "completed_by" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateCompletedBy() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateCompletedBy()
	})
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (u *InvoiceApplicationUpsertBulk) ClearCompletedBy() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearCompletedBy()
	})
}

// SetRejectedAt sets the "rejected_at" field.
func (u *InvoiceApplicationUpsertBulk) SetRejectedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRejectedAt(v)
	})
}

// UpdateRejectedAt sets the "rejected_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateRejectedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRejectedAt()
	})
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (u *InvoiceApplicationUpsertBulk) ClearRejectedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRejectedAt()
	})
}

// SetRejectedBy sets the "rejected_by" field.
func (u *InvoiceApplicationUpsertBulk) SetRejectedBy(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRejectedBy(v)
	})
}

// AddRejectedBy adds v to the "rejected_by" field.
func (u *InvoiceApplicationUpsertBulk) AddRejectedBy(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddRejectedBy(v)
	})
}

// UpdateRejectedBy sets the "rejected_by" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateRejectedBy() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRejectedBy()
	})
}

// ClearRejectedBy clears the value of the "rejected_by" field.
func (u *InvoiceApplicationUpsertBulk) ClearRejectedBy() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRejectedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateUpdatedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceApplicationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
