// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoicehistoricalmark"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceHistoricalMark is the model entity for the InvoiceHistoricalMark schema.
type InvoiceHistoricalMark struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID int64 `json:"source_id,omitempty"`
	// SourceReference holds the value of the "source_reference" field.
	SourceReference string `json:"source_reference,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// MarkedBy holds the value of the "marked_by" field.
	MarkedBy int64 `json:"marked_by,omitempty"`
	// MarkedAt holds the value of the "marked_at" field.
	MarkedAt time.Time `json:"marked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceHistoricalMarkQuery when eager-loading is set.
	Edges        InvoiceHistoricalMarkEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceHistoricalMarkEdges holds the relations/edges for other nodes in the graph.
type InvoiceHistoricalMarkEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceHistoricalMarkEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceHistoricalMark) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoicehistoricalmark.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case invoicehistoricalmark.FieldID, invoicehistoricalmark.FieldUserID, invoicehistoricalmark.FieldSourceID, invoicehistoricalmark.FieldMarkedBy:
			values[i] = new(sql.NullInt64)
		case invoicehistoricalmark.FieldSourceType, invoicehistoricalmark.FieldSourceReference:
			values[i] = new(sql.NullString)
		case invoicehistoricalmark.FieldMarkedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceHistoricalMark fields.
func (_m *InvoiceHistoricalMark) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoicehistoricalmark.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoicehistoricalmark.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoicehistoricalmark.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case invoicehistoricalmark.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.Int64
			}
		case invoicehistoricalmark.FieldSourceReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_reference", values[i])
			} else if value.Valid {
				_m.SourceReference = value.String
			}
		case invoicehistoricalmark.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case invoicehistoricalmark.FieldMarkedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field marked_by", values[i])
			} else if value.Valid {
				_m.MarkedBy = value.Int64
			}
		case invoicehistoricalmark.FieldMarkedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field marked_at", values[i])
			} else if value.Valid {
				_m.MarkedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceHistoricalMark.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceHistoricalMark) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the InvoiceHistoricalMark entity.
func (_m *InvoiceHistoricalMark) QueryUser() *UserQuery {
	return NewInvoiceHistoricalMarkClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this InvoiceHistoricalMark.
// Note that you need to call InvoiceHistoricalMark.Unwrap() before calling this method if this InvoiceHistoricalMark
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceHistoricalMark) Update() *InvoiceHistoricalMarkUpdateOne {
	return NewInvoiceHistoricalMarkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceHistoricalMark entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceHistoricalMark) Unwrap() *InvoiceHistoricalMark {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceHistoricalMark is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceHistoricalMark) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceHistoricalMark(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceID))
	builder.WriteString(", ")
	builder.WriteString("source_reference=")
	builder.WriteString(_m.SourceReference)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("marked_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.MarkedBy))
	builder.WriteString(", ")
	builder.WriteString("marked_at=")
	builder.WriteString(_m.MarkedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceHistoricalMarks is a parsable slice of InvoiceHistoricalMark.
type InvoiceHistoricalMarks []*InvoiceHistoricalMark
