// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceApplicationItemUpdate is the builder for updating InvoiceApplicationItem entities.
type InvoiceApplicationItemUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceApplicationItemMutation
}

// Where appends a list predicates to the InvoiceApplicationItemUpdate builder.
func (_u *InvoiceApplicationItemUpdate) Where(ps ...predicate.InvoiceApplicationItem) *InvoiceApplicationItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetApplicationID sets the "application_id" field.
func (_u *InvoiceApplicationItemUpdate) SetApplicationID(v int64) *InvoiceApplicationItemUpdate {
	_u.mutation.SetApplicationID(v)
	return _u
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdate) SetNillableApplicationID(v *int64) *InvoiceApplicationItemUpdate {
	if v != nil {
		_u.SetApplicationID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *InvoiceApplicationItemUpdate) SetSourceType(v string) *InvoiceApplicationItemUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdate) SetNillableSourceType(v *string) *InvoiceApplicationItemUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *InvoiceApplicationItemUpdate) SetSourceID(v int64) *InvoiceApplicationItemUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdate) SetNillableSourceID(v *int64) *InvoiceApplicationItemUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *InvoiceApplicationItemUpdate) AddSourceID(v int64) *InvoiceApplicationItemUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetSourceReference sets the "source_reference" field.
func (_u *InvoiceApplicationItemUpdate) SetSourceReference(v string) *InvoiceApplicationItemUpdate {
	_u.mutation.SetSourceReference(v)
	return _u
}

// SetNillableSourceReference sets the "source_reference" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdate) SetNillableSourceReference(v *string) *InvoiceApplicationItemUpdate {
	if v != nil {
		_u.SetSourceReference(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceApplicationItemUpdate) SetAmount(v float64) *InvoiceApplicationItemUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdate) SetNillableAmount(v *float64) *InvoiceApplicationItemUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceApplicationItemUpdate) AddAmount(v float64) *InvoiceApplicationItemUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetApplication sets the "application" edge to the InvoiceApplication entity.
func (_u *InvoiceApplicationItemUpdate) SetApplication(v *InvoiceApplication) *InvoiceApplicationItemUpdate {
	return _u.SetApplicationID(v.ID)
}

// Mutation returns the InvoiceApplicationItemMutation object of the builder.
func (_u *InvoiceApplicationItemUpdate) Mutation() *InvoiceApplicationItemMutation {
	return _u.mutation
}

// ClearApplication clears the "application" edge to the InvoiceApplication entity.
func (_u *InvoiceApplicationItemUpdate) ClearApplication() *InvoiceApplicationItemUpdate {
	_u.mutation.ClearApplication()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceApplicationItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceApplicationItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationItemUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := invoiceapplicationitem.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationItem.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceReference(); ok {
		if err := invoiceapplicationitem.SourceReferenceValidator(v); err != nil {
			return &ValidationError{Name: "source_reference", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationItem.source_reference": %w`, err)}
		}
	}
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplicationItem.application"`)
	}
	return nil
}

func (_u *InvoiceApplicationItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplicationitem.Table, invoiceapplicationitem.Columns, sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(invoiceapplicationitem.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(invoiceapplicationitem.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(invoiceapplicationitem.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceReference(); ok {
		_spec.SetField(invoiceapplicationitem.FieldSourceReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoiceapplicationitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoiceapplicationitem.FieldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationitem.ApplicationTable,
			Columns: []string{invoiceapplicationitem.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationitem.ApplicationTable,
			Columns: []string{invoiceapplicationitem.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplicationitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceApplicationItemUpdateOne is the builder for updating a single InvoiceApplicationItem entity.
type InvoiceApplicationItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceApplicationItemMutation
}

// SetApplicationID sets the "application_id" field.
func (_u *InvoiceApplicationItemUpdateOne) SetApplicationID(v int64) *InvoiceApplicationItemUpdateOne {
	_u.mutation.SetApplicationID(v)
	return _u
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdateOne) SetNillableApplicationID(v *int64) *InvoiceApplicationItemUpdateOne {
	if v != nil {
		_u.SetApplicationID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *InvoiceApplicationItemUpdateOne) SetSourceType(v string) *InvoiceApplicationItemUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdateOne) SetNillableSourceType(v *string) *InvoiceApplicationItemUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *InvoiceApplicationItemUpdateOne) SetSourceID(v int64) *InvoiceApplicationItemUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdateOne) SetNillableSourceID(v *int64) *InvoiceApplicationItemUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *InvoiceApplicationItemUpdateOne) AddSourceID(v int64) *InvoiceApplicationItemUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetSourceReference sets the "source_reference" field.
func (_u *InvoiceApplicationItemUpdateOne) SetSourceReference(v string) *InvoiceApplicationItemUpdateOne {
	_u.mutation.SetSourceReference(v)
	return _u
}

// SetNillableSourceReference sets the "source_reference" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdateOne) SetNillableSourceReference(v *string) *InvoiceApplicationItemUpdateOne {
	if v != nil {
		_u.SetSourceReference(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceApplicationItemUpdateOne) SetAmount(v float64) *InvoiceApplicationItemUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceApplicationItemUpdateOne) SetNillableAmount(v *float64) *InvoiceApplicationItemUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceApplicationItemUpdateOne) AddAmount(v float64) *InvoiceApplicationItemUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetApplication sets the "application" edge to the InvoiceApplication entity.
func (_u *InvoiceApplicationItemUpdateOne) SetApplication(v *InvoiceApplication) *InvoiceApplicationItemUpdateOne {
	return _u.SetApplicationID(v.ID)
}

// Mutation returns the InvoiceApplicationItemMutation object of the builder.
func (_u *InvoiceApplicationItemUpdateOne) Mutation() *InvoiceApplicationItemMutation {
	return _u.mutation
}

// ClearApplication clears the "application" edge to the InvoiceApplication entity.
func (_u *InvoiceApplicationItemUpdateOne) ClearApplication() *InvoiceApplicationItemUpdateOne {
	_u.mutation.ClearApplication()
	return _u
}

// Where appends a list predicates to the InvoiceApplicationItemUpdate builder.
func (_u *InvoiceApplicationItemUpdateOne) Where(ps ...predicate.InvoiceApplicationItem) *InvoiceApplicationItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceApplicationItemUpdateOne) Select(field string, fields ...string) *InvoiceApplicationItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceApplicationItem entity.
func (_u *InvoiceApplicationItemUpdateOne) Save(ctx context.Context) (*InvoiceApplicationItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationItemUpdateOne) SaveX(ctx context.Context) *InvoiceApplicationItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceApplicationItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationItemUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := invoiceapplicationitem.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationItem.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceReference(); ok {
		if err := invoiceapplicationitem.SourceReferenceValidator(v); err != nil {
			return &ValidationError{Name: "source_reference", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationItem.source_reference": %w`, err)}
		}
	}
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplicationItem.application"`)
	}
	return nil
}

func (_u *InvoiceApplicationItemUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceApplicationItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplicationitem.Table, invoiceapplicationitem.Columns, sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceApplicationItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceapplicationitem.FieldID)
		for _, f := range fields {
			if !invoiceapplicationitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceapplicationitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(invoiceapplicationitem.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(invoiceapplicationitem.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(invoiceapplicationitem.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceReference(); ok {
		_spec.SetField(invoiceapplicationitem.FieldSourceReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoiceapplicationitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoiceapplicationitem.FieldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationitem.ApplicationTable,
			Columns: []string{invoiceapplicationitem.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationitem.ApplicationTable,
			Columns: []string{invoiceapplicationitem.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceApplicationItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplicationitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
