// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicehistoricalmark"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceHistoricalMarkCreate is the builder for creating a InvoiceHistoricalMark entity.
type InvoiceHistoricalMarkCreate struct {
	config
	mutation *InvoiceHistoricalMarkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceHistoricalMarkCreate) SetUserID(v int64) *InvoiceHistoricalMarkCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *InvoiceHistoricalMarkCreate) SetSourceType(v string) *InvoiceHistoricalMarkCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *InvoiceHistoricalMarkCreate) SetSourceID(v int64) *InvoiceHistoricalMarkCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetSourceReference sets the "source_reference" field.
func (_c *InvoiceHistoricalMarkCreate) SetSourceReference(v string) *InvoiceHistoricalMarkCreate {
	_c.mutation.SetSourceReference(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceHistoricalMarkCreate) SetAmount(v float64) *InvoiceHistoricalMarkCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetMarkedBy sets the "marked_by" field.
func (_c *InvoiceHistoricalMarkCreate) SetMarkedBy(v int64) *InvoiceHistoricalMarkCreate {
	_c.mutation.SetMarkedBy(v)
	return _c
}

// SetMarkedAt sets the "marked_at" field.
func (_c *InvoiceHistoricalMarkCreate) SetMarkedAt(v time.Time) *InvoiceHistoricalMarkCreate {
	_c.mutation.SetMarkedAt(v)
	return _c
}

// SetNillableMarkedAt sets the "marked_at" field if the given value is not nil.
func (_c *InvoiceHistoricalMarkCreate) SetNillableMarkedAt(v *time.Time) *InvoiceHistoricalMarkCreate {
	if v != nil {
		_c.SetMarkedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *InvoiceHistoricalMarkCreate) SetUser(v *User) *InvoiceHistoricalMarkCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the InvoiceHistoricalMarkMutation object of the builder.
func (_c *InvoiceHistoricalMarkCreate) Mutation() *InvoiceHistoricalMarkMutation {
	return _c.mutation
}

// Save creates the InvoiceHistoricalMark in the database.
func (_c *InvoiceHistoricalMarkCreate) Save(ctx context.Context) (*InvoiceHistoricalMark, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceHistoricalMarkCreate) SaveX(ctx context.Context) *InvoiceHistoricalMark {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceHistoricalMarkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceHistoricalMarkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceHistoricalMarkCreate) defaults() {
	if _, ok := _c.mutation.MarkedAt(); !ok {
		v := invoicehistoricalmark.DefaultMarkedAt()
		_c.mutation.SetMarkedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceHistoricalMarkCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceHistoricalMark.user_id"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "InvoiceHistoricalMark.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := invoicehistoricalmark.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceHistoricalMark.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "InvoiceHistoricalMark.source_id"`)}
	}
	if _, ok := _c.mutation.SourceReference(); !ok {
		return &ValidationError{Name: "source_reference", err: errors.New(`ent: missing required field "InvoiceHistoricalMark.source_reference"`)}
	}
	if v, ok := _c.mutation.SourceReference(); ok {
		if err := invoicehistoricalmark.SourceReferenceValidator(v); err != nil {
			return &ValidationError{Name: "source_reference", err: fmt.Errorf(`ent: validator failed for field "InvoiceHistoricalMark.source_reference": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "InvoiceHistoricalMark.amount"`)}
	}
	if _, ok := _c.mutation.MarkedBy(); !ok {
		return &ValidationError{Name: "marked_by", err: errors.New(`ent: missing required field "InvoiceHistoricalMark.marked_by"`)}
	}
	if _, ok := _c.mutation.MarkedAt(); !ok {
		return &ValidationError{Name: "marked_at", err: errors.New(`ent: missing required field "InvoiceHistoricalMark.marked_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InvoiceHistoricalMark.user"`)}
	}
	return nil
}

func (_c *InvoiceHistoricalMarkCreate) sqlSave(ctx context.Context) (*InvoiceHistoricalMark, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceHistoricalMarkCreate) createSpec() (*InvoiceHistoricalMark, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceHistoricalMark{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicehistoricalmark.Table, sqlgraph.NewFieldSpec(invoicehistoricalmark.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(invoicehistoricalmark.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(invoicehistoricalmark.FieldSourceID, field.TypeInt64, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.SourceReference(); ok {
		_spec.SetField(invoicehistoricalmark.FieldSourceReference, field.TypeString, value)
		_node.SourceReference = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoicehistoricalmark.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.MarkedBy(); ok {
		_spec.SetField(invoicehistoricalmark.FieldMarkedBy, field.TypeInt64, value)
		_node.MarkedBy = value
	}
	if value, ok := _c.mutation.MarkedAt(); ok {
		_spec.SetField(invoicehistoricalmark.FieldMarkedAt, field.TypeTime, value)
		_node.MarkedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicehistoricalmark.UserTable,
			Columns: []string{invoicehistoricalmark.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceHistoricalMark.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceHistoricalMarkUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceHistoricalMarkCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceHistoricalMarkUpsertOne {
	_c.conflict = opts
	return &InvoiceHistoricalMarkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceHistoricalMark.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceHistoricalMarkCreate) OnConflictColumns(columns ...string) *InvoiceHistoricalMarkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceHistoricalMarkUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceHistoricalMarkUpsertOne is the builder for "upsert"-ing
	//  one InvoiceHistoricalMark node.
	InvoiceHistoricalMarkUpsertOne struct {
		create *InvoiceHistoricalMarkCreate
	}

	// InvoiceHistoricalMarkUpsert is the "OnConflict" setter.
	InvoiceHistoricalMarkUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceHistoricalMarkUpsert) SetUserID(v int64) *InvoiceHistoricalMarkUpsert {
	u.Set(invoicehistoricalmark.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsert) UpdateUserID() *InvoiceHistoricalMarkUpsert {
	u.SetExcluded(invoicehistoricalmark.FieldUserID)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *InvoiceHistoricalMarkUpsert) SetSourceType(v string) *InvoiceHistoricalMarkUpsert {
	u.Set(invoicehistoricalmark.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsert) UpdateSourceType() *InvoiceHistoricalMarkUpsert {
	u.SetExcluded(invoicehistoricalmark.FieldSourceType)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *InvoiceHistoricalMarkUpsert) SetSourceID(v int64) *InvoiceHistoricalMarkUpsert {
	u.Set(invoicehistoricalmark.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsert) UpdateSourceID() *InvoiceHistoricalMarkUpsert {
	u.SetExcluded(invoicehistoricalmark.FieldSourceID)
	return u
}

// AddSourceID adds v to the "source_id" field.
func (u *InvoiceHistoricalMarkUpsert) AddSourceID(v int64) *InvoiceHistoricalMarkUpsert {
	u.Add(invoicehistoricalmark.FieldSourceID, v)
	return u
}

// SetSourceReference sets the "source_reference" field.
func (u *InvoiceHistoricalMarkUpsert) SetSourceReference(v string) *InvoiceHistoricalMarkUpsert {
	u.Set(invoicehistoricalmark.FieldSourceReference, v)
	return u
}

// UpdateSourceReference sets the "source_reference" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsert) UpdateSourceReference() *InvoiceHistoricalMarkUpsert {
	u.SetExcluded(invoicehistoricalmark.FieldSourceReference)
	return u
}

// SetAmount sets the "amount" field.
func (u *InvoiceHistoricalMarkUpsert) SetAmount(v float64) *InvoiceHistoricalMarkUpsert {
	u.Set(invoicehistoricalmark.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsert) UpdateAmount() *InvoiceHistoricalMarkUpsert {
	u.SetExcluded(invoicehistoricalmark.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceHistoricalMarkUpsert) AddAmount(v float64) *InvoiceHistoricalMarkUpsert {
	u.Add(invoicehistoricalmark.FieldAmount, v)
	return u
}

// SetMarkedBy sets the "marked_by" field.
func (u *InvoiceHistoricalMarkUpsert) SetMarkedBy(v int64) *InvoiceHistoricalMarkUpsert {
	u.Set(invoicehistoricalmark.FieldMarkedBy, v)
	return u
}

// UpdateMarkedBy sets the "marked_by" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsert) UpdateMarkedBy() *InvoiceHistoricalMarkUpsert {
	u.SetExcluded(invoicehistoricalmark.FieldMarkedBy)
	return u
}

// AddMarkedBy adds v to the "marked_by" field.
func (u *InvoiceHistoricalMarkUpsert) AddMarkedBy(v int64) *InvoiceHistoricalMarkUpsert {
	u.Add(invoicehistoricalmark.FieldMarkedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceHistoricalMark.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceHistoricalMarkUpsertOne) UpdateNewValues() *InvoiceHistoricalMarkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.MarkedAt(); exists {
			s.SetIgnore(invoicehistoricalmark.FieldMarkedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceHistoricalMark.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceHistoricalMarkUpsertOne) Ignore() *InvoiceHistoricalMarkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceHistoricalMarkUpsertOne) DoNothing() *InvoiceHistoricalMarkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceHistoricalMarkCreate.OnConflict
// documentation for more info.
func (u *InvoiceHistoricalMarkUpsertOne) Update(set func(*InvoiceHistoricalMarkUpsert)) *InvoiceHistoricalMarkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceHistoricalMarkUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceHistoricalMarkUpsertOne) SetUserID(v int64) *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertOne) UpdateUserID() *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateUserID()
	})
}

// SetSourceType sets the "source_type" field.
func (u *InvoiceHistoricalMarkUpsertOne) SetSourceType(v string) *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertOne) UpdateSourceType() *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *InvoiceHistoricalMarkUpsertOne) SetSourceID(v int64) *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *InvoiceHistoricalMarkUpsertOne) AddSourceID(v int64) *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertOne) UpdateSourceID() *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateSourceID()
	})
}

// SetSourceReference sets the "source_reference" field.
func (u *InvoiceHistoricalMarkUpsertOne) SetSourceReference(v string) *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetSourceReference(v)
	})
}

// UpdateSourceReference sets the "source_reference" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertOne) UpdateSourceReference() *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateSourceReference()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceHistoricalMarkUpsertOne) SetAmount(v float64) *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceHistoricalMarkUpsertOne) AddAmount(v float64) *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertOne) UpdateAmount() *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateAmount()
	})
}

// SetMarkedBy sets the "marked_by" field.
func (u *InvoiceHistoricalMarkUpsertOne) SetMarkedBy(v int64) *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetMarkedBy(v)
	})
}

// AddMarkedBy adds v to the "marked_by" field.
func (u *InvoiceHistoricalMarkUpsertOne) AddMarkedBy(v int64) *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.AddMarkedBy(v)
	})
}

// UpdateMarkedBy sets the "marked_by" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertOne) UpdateMarkedBy() *InvoiceHistoricalMarkUpsertOne {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateMarkedBy()
	})
}

// Exec executes the query.
func (u *InvoiceHistoricalMarkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceHistoricalMarkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceHistoricalMarkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceHistoricalMarkUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceHistoricalMarkUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceHistoricalMarkCreateBulk is the builder for creating many InvoiceHistoricalMark entities in bulk.
type InvoiceHistoricalMarkCreateBulk struct {
	config
	err      error
	builders []*InvoiceHistoricalMarkCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceHistoricalMark entities in the database.
func (_c *InvoiceHistoricalMarkCreateBulk) Save(ctx context.Context) ([]*InvoiceHistoricalMark, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceHistoricalMark, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceHistoricalMarkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceHistoricalMarkCreateBulk) SaveX(ctx context.Context) []*InvoiceHistoricalMark {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceHistoricalMarkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceHistoricalMarkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceHistoricalMark.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceHistoricalMarkUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceHistoricalMarkCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceHistoricalMarkUpsertBulk {
	_c.conflict = opts
	return &InvoiceHistoricalMarkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceHistoricalMark.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceHistoricalMarkCreateBulk) OnConflictColumns(columns ...string) *InvoiceHistoricalMarkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceHistoricalMarkUpsertBulk{
		create: _c,
	}
}

// InvoiceHistoricalMarkUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceHistoricalMark nodes.
type InvoiceHistoricalMarkUpsertBulk struct {
	create *InvoiceHistoricalMarkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceHistoricalMark.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceHistoricalMarkUpsertBulk) UpdateNewValues() *InvoiceHistoricalMarkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.MarkedAt(); exists {
				s.SetIgnore(invoicehistoricalmark.FieldMarkedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceHistoricalMark.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceHistoricalMarkUpsertBulk) Ignore() *InvoiceHistoricalMarkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceHistoricalMarkUpsertBulk) DoNothing() *InvoiceHistoricalMarkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceHistoricalMarkCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceHistoricalMarkUpsertBulk) Update(set func(*InvoiceHistoricalMarkUpsert)) *InvoiceHistoricalMarkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceHistoricalMarkUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceHistoricalMarkUpsertBulk) SetUserID(v int64) *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertBulk) UpdateUserID() *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateUserID()
	})
}

// SetSourceType sets the "source_type" field.
func (u *InvoiceHistoricalMarkUpsertBulk) SetSourceType(v string) *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertBulk) UpdateSourceType() *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *InvoiceHistoricalMarkUpsertBulk) SetSourceID(v int64) *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *InvoiceHistoricalMarkUpsertBulk) AddSourceID(v int64) *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertBulk) UpdateSourceID() *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateSourceID()
	})
}

// SetSourceReference sets the "source_reference" field.
func (u *InvoiceHistoricalMarkUpsertBulk) SetSourceReference(v string) *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetSourceReference(v)
	})
}

// UpdateSourceReference sets the "source_reference" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertBulk) UpdateSourceReference() *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateSourceReference()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceHistoricalMarkUpsertBulk) SetAmount(v float64) *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceHistoricalMarkUpsertBulk) AddAmount(v float64) *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertBulk) UpdateAmount() *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateAmount()
	})
}

// SetMarkedBy sets the "marked_by" field.
func (u *InvoiceHistoricalMarkUpsertBulk) SetMarkedBy(v int64) *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.SetMarkedBy(v)
	})
}

// AddMarkedBy adds v to the "marked_by" field.
func (u *InvoiceHistoricalMarkUpsertBulk) AddMarkedBy(v int64) *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.AddMarkedBy(v)
	})
}

// UpdateMarkedBy sets the "marked_by" field to the value that was provided on create.
func (u *InvoiceHistoricalMarkUpsertBulk) UpdateMarkedBy() *InvoiceHistoricalMarkUpsertBulk {
	return u.Update(func(s *InvoiceHistoricalMarkUpsert) {
		s.UpdateMarkedBy()
	})
}

// Exec executes the query.
func (u *InvoiceHistoricalMarkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceHistoricalMarkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceHistoricalMarkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceHistoricalMarkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
