// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationitem"
)

// InvoiceApplicationItemCreate is the builder for creating a InvoiceApplicationItem entity.
type InvoiceApplicationItemCreate struct {
	config
	mutation *InvoiceApplicationItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetApplicationID sets the "application_id" field.
func (_c *InvoiceApplicationItemCreate) SetApplicationID(v int64) *InvoiceApplicationItemCreate {
	_c.mutation.SetApplicationID(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *InvoiceApplicationItemCreate) SetSourceType(v string) *InvoiceApplicationItemCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *InvoiceApplicationItemCreate) SetSourceID(v int64) *InvoiceApplicationItemCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetSourceReference sets the "source_reference" field.
func (_c *InvoiceApplicationItemCreate) SetSourceReference(v string) *InvoiceApplicationItemCreate {
	_c.mutation.SetSourceReference(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceApplicationItemCreate) SetAmount(v float64) *InvoiceApplicationItemCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceApplicationItemCreate) SetCreatedAt(v time.Time) *InvoiceApplicationItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceApplicationItemCreate) SetNillableCreatedAt(v *time.Time) *InvoiceApplicationItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetApplication sets the "application" edge to the InvoiceApplication entity.
func (_c *InvoiceApplicationItemCreate) SetApplication(v *InvoiceApplication) *InvoiceApplicationItemCreate {
	return _c.SetApplicationID(v.ID)
}

// Mutation returns the InvoiceApplicationItemMutation object of the builder.
func (_c *InvoiceApplicationItemCreate) Mutation() *InvoiceApplicationItemMutation {
	return _c.mutation
}

// Save creates the InvoiceApplicationItem in the database.
func (_c *InvoiceApplicationItemCreate) Save(ctx context.Context) (*InvoiceApplicationItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceApplicationItemCreate) SaveX(ctx context.Context) *InvoiceApplicationItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceApplicationItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoiceapplicationitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceApplicationItemCreate) check() error {
	if _, ok := _c.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "InvoiceApplicationItem.application_id"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "InvoiceApplicationItem.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := invoiceapplicationitem.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationItem.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "InvoiceApplicationItem.source_id"`)}
	}
	if _, ok := _c.mutation.SourceReference(); !ok {
		return &ValidationError{Name: "source_reference", err: errors.New(`ent: missing required field "InvoiceApplicationItem.source_reference"`)}
	}
	if v, ok := _c.mutation.SourceReference(); ok {
		if err := invoiceapplicationitem.SourceReferenceValidator(v); err != nil {
			return &ValidationError{Name: "source_reference", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationItem.source_reference": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "InvoiceApplicationItem.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceApplicationItem.created_at"`)}
	}
	if len(_c.mutation.ApplicationIDs()) == 0 {
		return &ValidationError{Name: "application", err: errors.New(`ent: missing required edge "InvoiceApplicationItem.application"`)}
	}
	return nil
}

func (_c *InvoiceApplicationItemCreate) sqlSave(ctx context.Context) (*InvoiceApplicationItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceApplicationItemCreate) createSpec() (*InvoiceApplicationItem, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceApplicationItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoiceapplicationitem.Table, sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(invoiceapplicationitem.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(invoiceapplicationitem.FieldSourceID, field.TypeInt64, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.SourceReference(); ok {
		_spec.SetField(invoiceapplicationitem.FieldSourceReference, field.TypeString, value)
		_node.SourceReference = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoiceapplicationitem.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoiceapplicationitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationitem.ApplicationTable,
			Columns: []string{invoiceapplicationitem.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApplicationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplicationItem.Create().
//		SetApplicationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationItemUpsert) {
//			SetApplicationID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationItemCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationItemUpsertOne {
	_c.conflict = opts
	return &InvoiceApplicationItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplicationItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationItemCreate) OnConflictColumns(columns ...string) *InvoiceApplicationItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationItemUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceApplicationItemUpsertOne is the builder for "upsert"-ing
	//  one InvoiceApplicationItem node.
	InvoiceApplicationItemUpsertOne struct {
		create *InvoiceApplicationItemCreate
	}

	// InvoiceApplicationItemUpsert is the "OnConflict" setter.
	InvoiceApplicationItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetApplicationID sets the "application_id" field.
func (u *InvoiceApplicationItemUpsert) SetApplicationID(v int64) *InvoiceApplicationItemUpsert {
	u.Set(invoiceapplicationitem.FieldApplicationID, v)
	return u
}

// UpdateApplicationID sets the "application_id" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsert) UpdateApplicationID() *InvoiceApplicationItemUpsert {
	u.SetExcluded(invoiceapplicationitem.FieldApplicationID)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *InvoiceApplicationItemUpsert) SetSourceType(v string) *InvoiceApplicationItemUpsert {
	u.Set(invoiceapplicationitem.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsert) UpdateSourceType() *InvoiceApplicationItemUpsert {
	u.SetExcluded(invoiceapplicationitem.FieldSourceType)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *InvoiceApplicationItemUpsert) SetSourceID(v int64) *InvoiceApplicationItemUpsert {
	u.Set(invoiceapplicationitem.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsert) UpdateSourceID() *InvoiceApplicationItemUpsert {
	u.SetExcluded(invoiceapplicationitem.FieldSourceID)
	return u
}

// AddSourceID adds v to the "source_id" field.
func (u *InvoiceApplicationItemUpsert) AddSourceID(v int64) *InvoiceApplicationItemUpsert {
	u.Add(invoiceapplicationitem.FieldSourceID, v)
	return u
}

// SetSourceReference sets the "source_reference" field.
func (u *InvoiceApplicationItemUpsert) SetSourceReference(v string) *InvoiceApplicationItemUpsert {
	u.Set(invoiceapplicationitem.FieldSourceReference, v)
	return u
}

// UpdateSourceReference sets the "source_reference" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsert) UpdateSourceReference() *InvoiceApplicationItemUpsert {
	u.SetExcluded(invoiceapplicationitem.FieldSourceReference)
	return u
}

// SetAmount sets the "amount" field.
func (u *InvoiceApplicationItemUpsert) SetAmount(v float64) *InvoiceApplicationItemUpsert {
	u.Set(invoiceapplicationitem.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsert) UpdateAmount() *InvoiceApplicationItemUpsert {
	u.SetExcluded(invoiceapplicationitem.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceApplicationItemUpsert) AddAmount(v float64) *InvoiceApplicationItemUpsert {
	u.Add(invoiceapplicationitem.FieldAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceApplicationItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationItemUpsertOne) UpdateNewValues() *InvoiceApplicationItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoiceapplicationitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplicationItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceApplicationItemUpsertOne) Ignore() *InvoiceApplicationItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationItemUpsertOne) DoNothing() *InvoiceApplicationItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationItemCreate.OnConflict
// documentation for more info.
func (u *InvoiceApplicationItemUpsertOne) Update(set func(*InvoiceApplicationItemUpsert)) *InvoiceApplicationItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetApplicationID sets the "application_id" field.
func (u *InvoiceApplicationItemUpsertOne) SetApplicationID(v int64) *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetApplicationID(v)
	})
}

// UpdateApplicationID sets the "application_id" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertOne) UpdateApplicationID() *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateApplicationID()
	})
}

// SetSourceType sets the "source_type" field.
func (u *InvoiceApplicationItemUpsertOne) SetSourceType(v string) *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertOne) UpdateSourceType() *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *InvoiceApplicationItemUpsertOne) SetSourceID(v int64) *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *InvoiceApplicationItemUpsertOne) AddSourceID(v int64) *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertOne) UpdateSourceID() *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateSourceID()
	})
}

// SetSourceReference sets the "source_reference" field.
func (u *InvoiceApplicationItemUpsertOne) SetSourceReference(v string) *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetSourceReference(v)
	})
}

// UpdateSourceReference sets the "source_reference" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertOne) UpdateSourceReference() *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateSourceReference()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceApplicationItemUpsertOne) SetAmount(v float64) *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceApplicationItemUpsertOne) AddAmount(v float64) *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertOne) UpdateAmount() *InvoiceApplicationItemUpsertOne {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceApplicationItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceApplicationItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceApplicationItemCreateBulk is the builder for creating many InvoiceApplicationItem entities in bulk.
type InvoiceApplicationItemCreateBulk struct {
	config
	err      error
	builders []*InvoiceApplicationItemCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceApplicationItem entities in the database.
func (_c *InvoiceApplicationItemCreateBulk) Save(ctx context.Context) ([]*InvoiceApplicationItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceApplicationItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceApplicationItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceApplicationItemCreateBulk) SaveX(ctx context.Context) []*InvoiceApplicationItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplicationItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationItemUpsert) {
//			SetApplicationID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationItemUpsertBulk {
	_c.conflict = opts
	return &InvoiceApplicationItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplicationItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationItemCreateBulk) OnConflictColumns(columns ...string) *InvoiceApplicationItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationItemUpsertBulk{
		create: _c,
	}
}

// InvoiceApplicationItemUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceApplicationItem nodes.
type InvoiceApplicationItemUpsertBulk struct {
	create *InvoiceApplicationItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceApplicationItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationItemUpsertBulk) UpdateNewValues() *InvoiceApplicationItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoiceapplicationitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplicationItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceApplicationItemUpsertBulk) Ignore() *InvoiceApplicationItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationItemUpsertBulk) DoNothing() *InvoiceApplicationItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationItemCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceApplicationItemUpsertBulk) Update(set func(*InvoiceApplicationItemUpsert)) *InvoiceApplicationItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetApplicationID sets the "application_id" field.
func (u *InvoiceApplicationItemUpsertBulk) SetApplicationID(v int64) *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetApplicationID(v)
	})
}

// UpdateApplicationID sets the "application_id" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertBulk) UpdateApplicationID() *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateApplicationID()
	})
}

// SetSourceType sets the "source_type" field.
func (u *InvoiceApplicationItemUpsertBulk) SetSourceType(v string) *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertBulk) UpdateSourceType() *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *InvoiceApplicationItemUpsertBulk) SetSourceID(v int64) *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *InvoiceApplicationItemUpsertBulk) AddSourceID(v int64) *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertBulk) UpdateSourceID() *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateSourceID()
	})
}

// SetSourceReference sets the "source_reference" field.
func (u *InvoiceApplicationItemUpsertBulk) SetSourceReference(v string) *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetSourceReference(v)
	})
}

// UpdateSourceReference sets the "source_reference" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertBulk) UpdateSourceReference() *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateSourceReference()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceApplicationItemUpsertBulk) SetAmount(v float64) *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceApplicationItemUpsertBulk) AddAmount(v float64) *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceApplicationItemUpsertBulk) UpdateAmount() *InvoiceApplicationItemUpsertBulk {
	return u.Update(func(s *InvoiceApplicationItemUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceApplicationItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
