// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceApplicationItemQuery is the builder for querying InvoiceApplicationItem entities.
type InvoiceApplicationItemQuery struct {
	config
	ctx             *QueryContext
	order           []invoiceapplicationitem.OrderOption
	inters          []Interceptor
	predicates      []predicate.InvoiceApplicationItem
	withApplication *InvoiceApplicationQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InvoiceApplicationItemQuery builder.
func (_q *InvoiceApplicationItemQuery) Where(ps ...predicate.InvoiceApplicationItem) *InvoiceApplicationItemQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *InvoiceApplicationItemQuery) Limit(limit int) *InvoiceApplicationItemQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *InvoiceApplicationItemQuery) Offset(offset int) *InvoiceApplicationItemQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *InvoiceApplicationItemQuery) Unique(unique bool) *InvoiceApplicationItemQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *InvoiceApplicationItemQuery) Order(o ...invoiceapplicationitem.OrderOption) *InvoiceApplicationItemQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryApplication chains the current query on the "application" edge.
func (_q *InvoiceApplicationItemQuery) QueryApplication() *InvoiceApplicationQuery {
	query := (&InvoiceApplicationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(invoiceapplicationitem.Table, invoiceapplicationitem.FieldID, selector),
			sqlgraph.To(invoiceapplication.Table, invoiceapplication.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invoiceapplicationitem.ApplicationTable, invoiceapplicationitem.ApplicationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first InvoiceApplicationItem entity from the query.
// Returns a *NotFoundError when no InvoiceApplicationItem was found.
func (_q *InvoiceApplicationItemQuery) First(ctx context.Context) (*InvoiceApplicationItem, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{invoiceapplicationitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *InvoiceApplicationItemQuery) FirstX(ctx context.Context) *InvoiceApplicationItem {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InvoiceApplicationItem ID from the query.
// Returns a *NotFoundError when no InvoiceApplicationItem ID was found.
func (_q *InvoiceApplicationItemQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{invoiceapplicationitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *InvoiceApplicationItemQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InvoiceApplicationItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one InvoiceApplicationItem entity is found.
// Returns a *NotFoundError when no InvoiceApplicationItem entities are found.
func (_q *InvoiceApplicationItemQuery) Only(ctx context.Context) (*InvoiceApplicationItem, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{invoiceapplicationitem.Label}
	default:
		return nil, &NotSingularError{invoiceapplicationitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *InvoiceApplicationItemQuery) OnlyX(ctx context.Context) *InvoiceApplicationItem {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InvoiceApplicationItem ID in the query.
// Returns a *NotSingularError when more than one InvoiceApplicationItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *InvoiceApplicationItemQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{invoiceapplicationitem.Label}
	default:
		err = &NotSingularError{invoiceapplicationitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *InvoiceApplicationItemQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InvoiceApplicationItems.
func (_q *InvoiceApplicationItemQuery) All(ctx context.Context) ([]*InvoiceApplicationItem, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*InvoiceApplicationItem, *InvoiceApplicationItemQuery]()
	return withInterceptors[[]*InvoiceApplicationItem](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *InvoiceApplicationItemQuery) AllX(ctx context.Context) []*InvoiceApplicationItem {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InvoiceApplicationItem IDs.
func (_q *InvoiceApplicationItemQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(invoiceapplicationitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *InvoiceApplicationItemQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *InvoiceApplicationItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*InvoiceApplicationItemQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *InvoiceApplicationItemQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *InvoiceApplicationItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *InvoiceApplicationItemQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InvoiceApplicationItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *InvoiceApplicationItemQuery) Clone() *InvoiceApplicationItemQuery {
	if _q == nil {
		return nil
	}
	return &InvoiceApplicationItemQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]invoiceapplicationitem.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.InvoiceApplicationItem{}, _q.predicates...),
		withApplication: _q.withApplication.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithApplication tells the query-builder to eager-load the nodes that are connected to
// the "application" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InvoiceApplicationItemQuery) WithApplication(opts ...func(*InvoiceApplicationQuery)) *InvoiceApplicationItemQuery {
	query := (&InvoiceApplicationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withApplication = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ApplicationID int64 `json:"application_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InvoiceApplicationItem.Query().
//		GroupBy(invoiceapplicationitem.FieldApplicationID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *InvoiceApplicationItemQuery) GroupBy(field string, fields ...string) *InvoiceApplicationItemGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InvoiceApplicationItemGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = invoiceapplicationitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ApplicationID int64 `json:"application_id,omitempty"`
//	}
//
//	client.InvoiceApplicationItem.Query().
//		Select(invoiceapplicationitem.FieldApplicationID).
//		Scan(ctx, &v)
func (_q *InvoiceApplicationItemQuery) Select(fields ...string) *InvoiceApplicationItemSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &InvoiceApplicationItemSelect{InvoiceApplicationItemQuery: _q}
	sbuild.label = invoiceapplicationitem.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InvoiceApplicationItemSelect configured with the given aggregations.
func (_q *InvoiceApplicationItemQuery) Aggregate(fns ...AggregateFunc) *InvoiceApplicationItemSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *InvoiceApplicationItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !invoiceapplicationitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *InvoiceApplicationItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*InvoiceApplicationItem, error) {
	var (
		nodes       = []*InvoiceApplicationItem{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withApplication != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*InvoiceApplicationItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &InvoiceApplicationItem{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withApplication; query != nil {
		if err := _q.loadApplication(ctx, query, nodes, nil,
			func(n *InvoiceApplicationItem, e *InvoiceApplication) { n.Edges.Application = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *InvoiceApplicationItemQuery) loadApplication(ctx context.Context, query *InvoiceApplicationQuery, nodes []*InvoiceApplicationItem, init func(*InvoiceApplicationItem), assign func(*InvoiceApplicationItem, *InvoiceApplication)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*InvoiceApplicationItem)
	for i := range nodes {
		fk := nodes[i].ApplicationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(invoiceapplication.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "application_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *InvoiceApplicationItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *InvoiceApplicationItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(invoiceapplicationitem.Table, invoiceapplicationitem.Columns, sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceapplicationitem.FieldID)
		for i := range fields {
			if fields[i] != invoiceapplicationitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withApplication != nil {
			_spec.Node.AddColumnOnce(invoiceapplicationitem.FieldApplicationID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *InvoiceApplicationItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(invoiceapplicationitem.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = invoiceapplicationitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *InvoiceApplicationItemQuery) ForUpdate(opts ...sql.LockOption) *InvoiceApplicationItemQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *InvoiceApplicationItemQuery) ForShare(opts ...sql.LockOption) *InvoiceApplicationItemQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// InvoiceApplicationItemGroupBy is the group-by builder for InvoiceApplicationItem entities.
type InvoiceApplicationItemGroupBy struct {
	selector
	build *InvoiceApplicationItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *InvoiceApplicationItemGroupBy) Aggregate(fns ...AggregateFunc) *InvoiceApplicationItemGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *InvoiceApplicationItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvoiceApplicationItemQuery, *InvoiceApplicationItemGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *InvoiceApplicationItemGroupBy) sqlScan(ctx context.Context, root *InvoiceApplicationItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InvoiceApplicationItemSelect is the builder for selecting fields of InvoiceApplicationItem entities.
type InvoiceApplicationItemSelect struct {
	*InvoiceApplicationItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *InvoiceApplicationItemSelect) Aggregate(fns ...AggregateFunc) *InvoiceApplicationItemSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *InvoiceApplicationItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvoiceApplicationItemQuery, *InvoiceApplicationItemSelect](ctx, _s.InvoiceApplicationItemQuery, _s, _s.inters, v)
}

func (_s *InvoiceApplicationItemSelect) sqlScan(ctx context.Context, root *InvoiceApplicationItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
