// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceprofile"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceProfileCreate is the builder for creating a InvoiceProfile entity.
type InvoiceProfileCreate struct {
	config
	mutation *InvoiceProfileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceProfileCreate) SetUserID(v int64) *InvoiceProfileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *InvoiceProfileCreate) SetEmail(v string) *InvoiceProfileCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetTaxNumber sets the "tax_number" field.
func (_c *InvoiceProfileCreate) SetTaxNumber(v string) *InvoiceProfileCreate {
	_c.mutation.SetTaxNumber(v)
	return _c
}

// SetCompanyName sets the "company_name" field.
func (_c *InvoiceProfileCreate) SetCompanyName(v string) *InvoiceProfileCreate {
	_c.mutation.SetCompanyName(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceProfileCreate) SetCreatedAt(v time.Time) *InvoiceProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceProfileCreate) SetNillableCreatedAt(v *time.Time) *InvoiceProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceProfileCreate) SetUpdatedAt(v time.Time) *InvoiceProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceProfileCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *InvoiceProfileCreate) SetUser(v *User) *InvoiceProfileCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the InvoiceProfileMutation object of the builder.
func (_c *InvoiceProfileCreate) Mutation() *InvoiceProfileMutation {
	return _c.mutation
}

// Save creates the InvoiceProfile in the database.
func (_c *InvoiceProfileCreate) Save(ctx context.Context) (*InvoiceProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceProfileCreate) SaveX(ctx context.Context) *InvoiceProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoiceprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoiceprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceProfileCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceProfile.user_id"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "InvoiceProfile.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := invoiceprofile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxNumber(); !ok {
		return &ValidationError{Name: "tax_number", err: errors.New(`ent: missing required field "InvoiceProfile.tax_number"`)}
	}
	if v, ok := _c.mutation.TaxNumber(); ok {
		if err := invoiceprofile.TaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.tax_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CompanyName(); !ok {
		return &ValidationError{Name: "company_name", err: errors.New(`ent: missing required field "InvoiceProfile.company_name"`)}
	}
	if v, ok := _c.mutation.CompanyName(); ok {
		if err := invoiceprofile.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.company_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceProfile.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InvoiceProfile.user"`)}
	}
	return nil
}

func (_c *InvoiceProfileCreate) sqlSave(ctx context.Context) (*InvoiceProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceProfileCreate) createSpec() (*InvoiceProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoiceprofile.Table, sqlgraph.NewFieldSpec(invoiceprofile.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(invoiceprofile.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.TaxNumber(); ok {
		_spec.SetField(invoiceprofile.FieldTaxNumber, field.TypeString, value)
		_node.TaxNumber = value
	}
	if value, ok := _c.mutation.CompanyName(); ok {
		_spec.SetField(invoiceprofile.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoiceprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invoiceprofile.UserTable,
			Columns: []string{invoiceprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceProfile.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceProfileUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceProfileCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceProfileUpsertOne {
	_c.conflict = opts
	return &InvoiceProfileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceProfileCreate) OnConflictColumns(columns ...string) *InvoiceProfileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceProfileUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceProfileUpsertOne is the builder for "upsert"-ing
	//  one InvoiceProfile node.
	InvoiceProfileUpsertOne struct {
		create *InvoiceProfileCreate
	}

	// InvoiceProfileUpsert is the "OnConflict" setter.
	InvoiceProfileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceProfileUpsert) SetUserID(v int64) *InvoiceProfileUpsert {
	u.Set(invoiceprofile.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceProfileUpsert) UpdateUserID() *InvoiceProfileUpsert {
	u.SetExcluded(invoiceprofile.FieldUserID)
	return u
}

// SetEmail sets the "email" field.
func (u *InvoiceProfileUpsert) SetEmail(v string) *InvoiceProfileUpsert {
	u.Set(invoiceprofile.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceProfileUpsert) UpdateEmail() *InvoiceProfileUpsert {
	u.SetExcluded(invoiceprofile.FieldEmail)
	return u
}

// SetTaxNumber sets the "tax_number" field.
func (u *InvoiceProfileUpsert) SetTaxNumber(v string) *InvoiceProfileUpsert {
	u.Set(invoiceprofile.FieldTaxNumber, v)
	return u
}

// UpdateTaxNumber sets the "tax_number" field to the value that was provided on create.
func (u *InvoiceProfileUpsert) UpdateTaxNumber() *InvoiceProfileUpsert {
	u.SetExcluded(invoiceprofile.FieldTaxNumber)
	return u
}

// SetCompanyName sets the "company_name" field.
func (u *InvoiceProfileUpsert) SetCompanyName(v string) *InvoiceProfileUpsert {
	u.Set(invoiceprofile.FieldCompanyName, v)
	return u
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *InvoiceProfileUpsert) UpdateCompanyName() *InvoiceProfileUpsert {
	u.SetExcluded(invoiceprofile.FieldCompanyName)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceProfileUpsert) SetUpdatedAt(v time.Time) *InvoiceProfileUpsert {
	u.Set(invoiceprofile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceProfileUpsert) UpdateUpdatedAt() *InvoiceProfileUpsert {
	u.SetExcluded(invoiceprofile.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceProfileUpsertOne) UpdateNewValues() *InvoiceProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoiceprofile.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceProfile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceProfileUpsertOne) Ignore() *InvoiceProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceProfileUpsertOne) DoNothing() *InvoiceProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceProfileCreate.OnConflict
// documentation for more info.
func (u *InvoiceProfileUpsertOne) Update(set func(*InvoiceProfileUpsert)) *InvoiceProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceProfileUpsertOne) SetUserID(v int64) *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceProfileUpsertOne) UpdateUserID() *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateUserID()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceProfileUpsertOne) SetEmail(v string) *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceProfileUpsertOne) UpdateEmail() *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateEmail()
	})
}

// SetTaxNumber sets the "tax_number" field.
func (u *InvoiceProfileUpsertOne) SetTaxNumber(v string) *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetTaxNumber(v)
	})
}

// UpdateTaxNumber sets the "tax_number" field to the value that was provided on create.
func (u *InvoiceProfileUpsertOne) UpdateTaxNumber() *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateTaxNumber()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *InvoiceProfileUpsertOne) SetCompanyName(v string) *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *InvoiceProfileUpsertOne) UpdateCompanyName() *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateCompanyName()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceProfileUpsertOne) SetUpdatedAt(v time.Time) *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceProfileUpsertOne) UpdateUpdatedAt() *InvoiceProfileUpsertOne {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceProfileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceProfileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceProfileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceProfileUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceProfileUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceProfileCreateBulk is the builder for creating many InvoiceProfile entities in bulk.
type InvoiceProfileCreateBulk struct {
	config
	err      error
	builders []*InvoiceProfileCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceProfile entities in the database.
func (_c *InvoiceProfileCreateBulk) Save(ctx context.Context) ([]*InvoiceProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceProfileCreateBulk) SaveX(ctx context.Context) []*InvoiceProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceProfile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceProfileUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceProfileCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceProfileUpsertBulk {
	_c.conflict = opts
	return &InvoiceProfileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceProfileCreateBulk) OnConflictColumns(columns ...string) *InvoiceProfileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceProfileUpsertBulk{
		create: _c,
	}
}

// InvoiceProfileUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceProfile nodes.
type InvoiceProfileUpsertBulk struct {
	create *InvoiceProfileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceProfileUpsertBulk) UpdateNewValues() *InvoiceProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoiceprofile.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceProfile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceProfileUpsertBulk) Ignore() *InvoiceProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceProfileUpsertBulk) DoNothing() *InvoiceProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceProfileCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceProfileUpsertBulk) Update(set func(*InvoiceProfileUpsert)) *InvoiceProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceProfileUpsertBulk) SetUserID(v int64) *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceProfileUpsertBulk) UpdateUserID() *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateUserID()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceProfileUpsertBulk) SetEmail(v string) *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceProfileUpsertBulk) UpdateEmail() *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateEmail()
	})
}

// SetTaxNumber sets the "tax_number" field.
func (u *InvoiceProfileUpsertBulk) SetTaxNumber(v string) *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetTaxNumber(v)
	})
}

// UpdateTaxNumber sets the "tax_number" field to the value that was provided on create.
func (u *InvoiceProfileUpsertBulk) UpdateTaxNumber() *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateTaxNumber()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *InvoiceProfileUpsertBulk) SetCompanyName(v string) *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *InvoiceProfileUpsertBulk) UpdateCompanyName() *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateCompanyName()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceProfileUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceProfileUpsertBulk) UpdateUpdatedAt() *InvoiceProfileUpsertBulk {
	return u.Update(func(s *InvoiceProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceProfileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceProfileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceProfileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceProfileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
