// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceApplicationItemDelete is the builder for deleting a InvoiceApplicationItem entity.
type InvoiceApplicationItemDelete struct {
	config
	hooks    []Hook
	mutation *InvoiceApplicationItemMutation
}

// Where appends a list predicates to the InvoiceApplicationItemDelete builder.
func (_d *InvoiceApplicationItemDelete) Where(ps ...predicate.InvoiceApplicationItem) *InvoiceApplicationItemDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InvoiceApplicationItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceApplicationItemDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InvoiceApplicationItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(invoiceapplicationitem.Table, sqlgraph.NewFieldSpec(invoiceapplicationitem.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InvoiceApplicationItemDeleteOne is the builder for deleting a single InvoiceApplicationItem entity.
type InvoiceApplicationItemDeleteOne struct {
	_d *InvoiceApplicationItemDelete
}

// Where appends a list predicates to the InvoiceApplicationItemDelete builder.
func (_d *InvoiceApplicationItemDeleteOne) Where(ps ...predicate.InvoiceApplicationItem) *InvoiceApplicationItemDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InvoiceApplicationItemDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoiceapplicationitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceApplicationItemDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
