// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicehistoricalmark"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceHistoricalMarkUpdate is the builder for updating InvoiceHistoricalMark entities.
type InvoiceHistoricalMarkUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceHistoricalMarkMutation
}

// Where appends a list predicates to the InvoiceHistoricalMarkUpdate builder.
func (_u *InvoiceHistoricalMarkUpdate) Where(ps ...predicate.InvoiceHistoricalMark) *InvoiceHistoricalMarkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceHistoricalMarkUpdate) SetUserID(v int64) *InvoiceHistoricalMarkUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdate) SetNillableUserID(v *int64) *InvoiceHistoricalMarkUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *InvoiceHistoricalMarkUpdate) SetSourceType(v string) *InvoiceHistoricalMarkUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdate) SetNillableSourceType(v *string) *InvoiceHistoricalMarkUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *InvoiceHistoricalMarkUpdate) SetSourceID(v int64) *InvoiceHistoricalMarkUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdate) SetNillableSourceID(v *int64) *InvoiceHistoricalMarkUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *InvoiceHistoricalMarkUpdate) AddSourceID(v int64) *InvoiceHistoricalMarkUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetSourceReference sets the "source_reference" field.
func (_u *InvoiceHistoricalMarkUpdate) SetSourceReference(v string) *InvoiceHistoricalMarkUpdate {
	_u.mutation.SetSourceReference(v)
	return _u
}

// SetNillableSourceReference sets the "source_reference" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdate) SetNillableSourceReference(v *string) *InvoiceHistoricalMarkUpdate {
	if v != nil {
		_u.SetSourceReference(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceHistoricalMarkUpdate) SetAmount(v float64) *InvoiceHistoricalMarkUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdate) SetNillableAmount(v *float64) *InvoiceHistoricalMarkUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceHistoricalMarkUpdate) AddAmount(v float64) *InvoiceHistoricalMarkUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetMarkedBy sets the "marked_by" field.
func (_u *InvoiceHistoricalMarkUpdate) SetMarkedBy(v int64) *InvoiceHistoricalMarkUpdate {
	_u.mutation.ResetMarkedBy()
	_u.mutation.SetMarkedBy(v)
	return _u
}

// SetNillableMarkedBy sets the "marked_by" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdate) SetNillableMarkedBy(v *int64) *InvoiceHistoricalMarkUpdate {
	if v != nil {
		_u.SetMarkedBy(*v)
	}
	return _u
}

// AddMarkedBy adds value to the "marked_by" field.
func (_u *InvoiceHistoricalMarkUpdate) AddMarkedBy(v int64) *InvoiceHistoricalMarkUpdate {
	_u.mutation.AddMarkedBy(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceHistoricalMarkUpdate) SetUser(v *User) *InvoiceHistoricalMarkUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceHistoricalMarkMutation object of the builder.
func (_u *InvoiceHistoricalMarkUpdate) Mutation() *InvoiceHistoricalMarkMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceHistoricalMarkUpdate) ClearUser() *InvoiceHistoricalMarkUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceHistoricalMarkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceHistoricalMarkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceHistoricalMarkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceHistoricalMarkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceHistoricalMarkUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := invoicehistoricalmark.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceHistoricalMark.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceReference(); ok {
		if err := invoicehistoricalmark.SourceReferenceValidator(v); err != nil {
			return &ValidationError{Name: "source_reference", err: fmt.Errorf(`ent: validator failed for field "InvoiceHistoricalMark.source_reference": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceHistoricalMark.user"`)
	}
	return nil
}

func (_u *InvoiceHistoricalMarkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicehistoricalmark.Table, invoicehistoricalmark.Columns, sqlgraph.NewFieldSpec(invoicehistoricalmark.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(invoicehistoricalmark.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(invoicehistoricalmark.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(invoicehistoricalmark.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceReference(); ok {
		_spec.SetField(invoicehistoricalmark.FieldSourceReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoicehistoricalmark.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoicehistoricalmark.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MarkedBy(); ok {
		_spec.SetField(invoicehistoricalmark.FieldMarkedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMarkedBy(); ok {
		_spec.AddField(invoicehistoricalmark.FieldMarkedBy, field.TypeInt64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicehistoricalmark.UserTable,
			Columns: []string{invoicehistoricalmark.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicehistoricalmark.UserTable,
			Columns: []string{invoicehistoricalmark.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicehistoricalmark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceHistoricalMarkUpdateOne is the builder for updating a single InvoiceHistoricalMark entity.
type InvoiceHistoricalMarkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceHistoricalMarkMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceHistoricalMarkUpdateOne) SetUserID(v int64) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdateOne) SetNillableUserID(v *int64) *InvoiceHistoricalMarkUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *InvoiceHistoricalMarkUpdateOne) SetSourceType(v string) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdateOne) SetNillableSourceType(v *string) *InvoiceHistoricalMarkUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *InvoiceHistoricalMarkUpdateOne) SetSourceID(v int64) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdateOne) SetNillableSourceID(v *int64) *InvoiceHistoricalMarkUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *InvoiceHistoricalMarkUpdateOne) AddSourceID(v int64) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetSourceReference sets the "source_reference" field.
func (_u *InvoiceHistoricalMarkUpdateOne) SetSourceReference(v string) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.SetSourceReference(v)
	return _u
}

// SetNillableSourceReference sets the "source_reference" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdateOne) SetNillableSourceReference(v *string) *InvoiceHistoricalMarkUpdateOne {
	if v != nil {
		_u.SetSourceReference(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceHistoricalMarkUpdateOne) SetAmount(v float64) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdateOne) SetNillableAmount(v *float64) *InvoiceHistoricalMarkUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceHistoricalMarkUpdateOne) AddAmount(v float64) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetMarkedBy sets the "marked_by" field.
func (_u *InvoiceHistoricalMarkUpdateOne) SetMarkedBy(v int64) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.ResetMarkedBy()
	_u.mutation.SetMarkedBy(v)
	return _u
}

// SetNillableMarkedBy sets the "marked_by" field if the given value is not nil.
func (_u *InvoiceHistoricalMarkUpdateOne) SetNillableMarkedBy(v *int64) *InvoiceHistoricalMarkUpdateOne {
	if v != nil {
		_u.SetMarkedBy(*v)
	}
	return _u
}

// AddMarkedBy adds value to the "marked_by" field.
func (_u *InvoiceHistoricalMarkUpdateOne) AddMarkedBy(v int64) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.AddMarkedBy(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceHistoricalMarkUpdateOne) SetUser(v *User) *InvoiceHistoricalMarkUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceHistoricalMarkMutation object of the builder.
func (_u *InvoiceHistoricalMarkUpdateOne) Mutation() *InvoiceHistoricalMarkMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceHistoricalMarkUpdateOne) ClearUser() *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the InvoiceHistoricalMarkUpdate builder.
func (_u *InvoiceHistoricalMarkUpdateOne) Where(ps ...predicate.InvoiceHistoricalMark) *InvoiceHistoricalMarkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceHistoricalMarkUpdateOne) Select(field string, fields ...string) *InvoiceHistoricalMarkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceHistoricalMark entity.
func (_u *InvoiceHistoricalMarkUpdateOne) Save(ctx context.Context) (*InvoiceHistoricalMark, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceHistoricalMarkUpdateOne) SaveX(ctx context.Context) *InvoiceHistoricalMark {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceHistoricalMarkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceHistoricalMarkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceHistoricalMarkUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := invoicehistoricalmark.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceHistoricalMark.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceReference(); ok {
		if err := invoicehistoricalmark.SourceReferenceValidator(v); err != nil {
			return &ValidationError{Name: "source_reference", err: fmt.Errorf(`ent: validator failed for field "InvoiceHistoricalMark.source_reference": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceHistoricalMark.user"`)
	}
	return nil
}

func (_u *InvoiceHistoricalMarkUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceHistoricalMark, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicehistoricalmark.Table, invoicehistoricalmark.Columns, sqlgraph.NewFieldSpec(invoicehistoricalmark.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceHistoricalMark.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicehistoricalmark.FieldID)
		for _, f := range fields {
			if !invoicehistoricalmark.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoicehistoricalmark.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(invoicehistoricalmark.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(invoicehistoricalmark.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(invoicehistoricalmark.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceReference(); ok {
		_spec.SetField(invoicehistoricalmark.FieldSourceReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoicehistoricalmark.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoicehistoricalmark.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MarkedBy(); ok {
		_spec.SetField(invoicehistoricalmark.FieldMarkedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMarkedBy(); ok {
		_spec.AddField(invoicehistoricalmark.FieldMarkedBy, field.TypeInt64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicehistoricalmark.UserTable,
			Columns: []string{invoicehistoricalmark.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicehistoricalmark.UserTable,
			Columns: []string{invoicehistoricalmark.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceHistoricalMark{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicehistoricalmark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
