// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplication is the model entity for the InvoiceApplication schema.
type InvoiceApplication struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ApplicationNo holds the value of the "application_no" field.
	ApplicationNo string `json:"application_no,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// TaxNumber holds the value of the "tax_number" field.
	TaxNumber string `json:"tax_number,omitempty"`
	// CompanyName holds the value of the "company_name" field.
	CompanyName string `json:"company_name,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount float64 `json:"total_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RejectionReason holds the value of the "rejection_reason" field.
	RejectionReason *string `json:"rejection_reason,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CompletedBy holds the value of the "completed_by" field.
	CompletedBy *int64 `json:"completed_by,omitempty"`
	// RejectedAt holds the value of the "rejected_at" field.
	RejectedAt *time.Time `json:"rejected_at,omitempty"`
	// RejectedBy holds the value of the "rejected_by" field.
	RejectedBy *int64 `json:"rejected_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceApplicationQuery when eager-loading is set.
	Edges        InvoiceApplicationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceApplicationEdges holds the relations/edges for other nodes in the graph.
type InvoiceApplicationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Items holds the value of the items edge.
	Items []*InvoiceApplicationItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceApplicationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceApplicationEdges) ItemsOrErr() ([]*InvoiceApplicationItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceApplication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoiceapplication.FieldTotalAmount:
			values[i] = new(sql.NullFloat64)
		case invoiceapplication.FieldID, invoiceapplication.FieldUserID, invoiceapplication.FieldCompletedBy, invoiceapplication.FieldRejectedBy:
			values[i] = new(sql.NullInt64)
		case invoiceapplication.FieldApplicationNo, invoiceapplication.FieldEmail, invoiceapplication.FieldTaxNumber, invoiceapplication.FieldCompanyName, invoiceapplication.FieldStatus, invoiceapplication.FieldRejectionReason:
			values[i] = new(sql.NullString)
		case invoiceapplication.FieldCompletedAt, invoiceapplication.FieldRejectedAt, invoiceapplication.FieldCreatedAt, invoiceapplication.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceApplication fields.
func (_m *InvoiceApplication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoiceapplication.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoiceapplication.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoiceapplication.FieldApplicationNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field application_no", values[i])
			} else if value.Valid {
				_m.ApplicationNo = value.String
			}
		case invoiceapplication.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case invoiceapplication.FieldTaxNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_number", values[i])
			} else if value.Valid {
				_m.TaxNumber = value.String
			}
		case invoiceapplication.FieldCompanyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company_name", values[i])
			} else if value.Valid {
				_m.CompanyName = value.String
			}
		case invoiceapplication.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.Float64
			}
		case invoiceapplication.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoiceapplication.FieldRejectionReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rejection_reason", values[i])
			} else if value.Valid {
				_m.RejectionReason = new(string)
				*_m.RejectionReason = value.String
			}
		case invoiceapplication.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case invoiceapplication.FieldCompletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completed_by", values[i])
			} else if value.Valid {
				_m.CompletedBy = new(int64)
				*_m.CompletedBy = value.Int64
			}
		case invoiceapplication.FieldRejectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field rejected_at", values[i])
			} else if value.Valid {
				_m.RejectedAt = new(time.Time)
				*_m.RejectedAt = value.Time
			}
		case invoiceapplication.FieldRejectedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rejected_by", values[i])
			} else if value.Valid {
				_m.RejectedBy = new(int64)
				*_m.RejectedBy = value.Int64
			}
		case invoiceapplication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoiceapplication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceApplication.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceApplication) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the InvoiceApplication entity.
func (_m *InvoiceApplication) QueryUser() *UserQuery {
	return NewInvoiceApplicationClient(_m.config).QueryUser(_m)
}

// QueryItems queries the "items" edge of the InvoiceApplication entity.
func (_m *InvoiceApplication) QueryItems() *InvoiceApplicationItemQuery {
	return NewInvoiceApplicationClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this InvoiceApplication.
// Note that you need to call InvoiceApplication.Unwrap() before calling this method if this InvoiceApplication
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceApplication) Update() *InvoiceApplicationUpdateOne {
	return NewInvoiceApplicationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceApplication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceApplication) Unwrap() *InvoiceApplication {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceApplication is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceApplication) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceApplication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("application_no=")
	builder.WriteString(_m.ApplicationNo)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("tax_number=")
	builder.WriteString(_m.TaxNumber)
	builder.WriteString(", ")
	builder.WriteString("company_name=")
	builder.WriteString(_m.CompanyName)
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.RejectionReason; v != nil {
		builder.WriteString("rejection_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedBy; v != nil {
		builder.WriteString("completed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RejectedAt; v != nil {
		builder.WriteString("rejected_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RejectedBy; v != nil {
		builder.WriteString("rejected_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceApplications is a parsable slice of InvoiceApplication.
type InvoiceApplications []*InvoiceApplication
