// Code generated by ent, DO NOT EDIT.

package invoicehistoricalmark

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invoicehistoricalmark type in the database.
	Label = "invoice_historical_mark"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldSourceReference holds the string denoting the source_reference field in the database.
	FieldSourceReference = "source_reference"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldMarkedBy holds the string denoting the marked_by field in the database.
	FieldMarkedBy = "marked_by"
	// FieldMarkedAt holds the string denoting the marked_at field in the database.
	FieldMarkedAt = "marked_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the invoicehistoricalmark in the database.
	Table = "invoice_historical_marks"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "invoice_historical_marks"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for invoicehistoricalmark fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldSourceType,
	FieldSourceID,
	FieldSourceReference,
	FieldAmount,
	FieldMarkedBy,
	FieldMarkedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// SourceReferenceValidator is a validator for the "source_reference" field. It is called by the builders before save.
	SourceReferenceValidator func(string) error
	// DefaultMarkedAt holds the default value on creation for the "marked_at" field.
	DefaultMarkedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceHistoricalMark queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// BySourceReference orders the results by the source_reference field.
func BySourceReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceReference, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByMarkedBy orders the results by the marked_by field.
func ByMarkedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarkedBy, opts...).ToFunc()
}

// ByMarkedAt orders the results by the marked_at field.
func ByMarkedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarkedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
