// Code generated by ent, DO NOT EDIT.

package invoicehistoricalmark

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldUserID, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldSourceID, v))
}

// SourceReference applies equality check predicate on the "source_reference" field. It's identical to SourceReferenceEQ.
func SourceReference(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldSourceReference, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldAmount, v))
}

// MarkedBy applies equality check predicate on the "marked_by" field. It's identical to MarkedByEQ.
func MarkedBy(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldMarkedBy, v))
}

// MarkedAt applies equality check predicate on the "marked_at" field. It's identical to MarkedAtEQ.
func MarkedAt(v time.Time) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldMarkedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNotIn(FieldUserID, vs...))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLTE(FieldSourceID, v))
}

// SourceReferenceEQ applies the EQ predicate on the "source_reference" field.
func SourceReferenceEQ(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldSourceReference, v))
}

// SourceReferenceNEQ applies the NEQ predicate on the "source_reference" field.
func SourceReferenceNEQ(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNEQ(FieldSourceReference, v))
}

// SourceReferenceIn applies the In predicate on the "source_reference" field.
func SourceReferenceIn(vs ...string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldIn(FieldSourceReference, vs...))
}

// SourceReferenceNotIn applies the NotIn predicate on the "source_reference" field.
func SourceReferenceNotIn(vs ...string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNotIn(FieldSourceReference, vs...))
}

// SourceReferenceGT applies the GT predicate on the "source_reference" field.
func SourceReferenceGT(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGT(FieldSourceReference, v))
}

// SourceReferenceGTE applies the GTE predicate on the "source_reference" field.
func SourceReferenceGTE(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGTE(FieldSourceReference, v))
}

// SourceReferenceLT applies the LT predicate on the "source_reference" field.
func SourceReferenceLT(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLT(FieldSourceReference, v))
}

// SourceReferenceLTE applies the LTE predicate on the "source_reference" field.
func SourceReferenceLTE(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLTE(FieldSourceReference, v))
}

// SourceReferenceContains applies the Contains predicate on the "source_reference" field.
func SourceReferenceContains(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldContains(FieldSourceReference, v))
}

// SourceReferenceHasPrefix applies the HasPrefix predicate on the "source_reference" field.
func SourceReferenceHasPrefix(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldHasPrefix(FieldSourceReference, v))
}

// SourceReferenceHasSuffix applies the HasSuffix predicate on the "source_reference" field.
func SourceReferenceHasSuffix(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldHasSuffix(FieldSourceReference, v))
}

// SourceReferenceEqualFold applies the EqualFold predicate on the "source_reference" field.
func SourceReferenceEqualFold(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEqualFold(FieldSourceReference, v))
}

// SourceReferenceContainsFold applies the ContainsFold predicate on the "source_reference" field.
func SourceReferenceContainsFold(v string) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldContainsFold(FieldSourceReference, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLTE(FieldAmount, v))
}

// MarkedByEQ applies the EQ predicate on the "marked_by" field.
func MarkedByEQ(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldMarkedBy, v))
}

// MarkedByNEQ applies the NEQ predicate on the "marked_by" field.
func MarkedByNEQ(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNEQ(FieldMarkedBy, v))
}

// MarkedByIn applies the In predicate on the "marked_by" field.
func MarkedByIn(vs ...int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldIn(FieldMarkedBy, vs...))
}

// MarkedByNotIn applies the NotIn predicate on the "marked_by" field.
func MarkedByNotIn(vs ...int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNotIn(FieldMarkedBy, vs...))
}

// MarkedByGT applies the GT predicate on the "marked_by" field.
func MarkedByGT(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGT(FieldMarkedBy, v))
}

// MarkedByGTE applies the GTE predicate on the "marked_by" field.
func MarkedByGTE(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGTE(FieldMarkedBy, v))
}

// MarkedByLT applies the LT predicate on the "marked_by" field.
func MarkedByLT(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLT(FieldMarkedBy, v))
}

// MarkedByLTE applies the LTE predicate on the "marked_by" field.
func MarkedByLTE(v int64) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLTE(FieldMarkedBy, v))
}

// MarkedAtEQ applies the EQ predicate on the "marked_at" field.
func MarkedAtEQ(v time.Time) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldEQ(FieldMarkedAt, v))
}

// MarkedAtNEQ applies the NEQ predicate on the "marked_at" field.
func MarkedAtNEQ(v time.Time) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNEQ(FieldMarkedAt, v))
}

// MarkedAtIn applies the In predicate on the "marked_at" field.
func MarkedAtIn(vs ...time.Time) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldIn(FieldMarkedAt, vs...))
}

// MarkedAtNotIn applies the NotIn predicate on the "marked_at" field.
func MarkedAtNotIn(vs ...time.Time) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldNotIn(FieldMarkedAt, vs...))
}

// MarkedAtGT applies the GT predicate on the "marked_at" field.
func MarkedAtGT(v time.Time) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGT(FieldMarkedAt, v))
}

// MarkedAtGTE applies the GTE predicate on the "marked_at" field.
func MarkedAtGTE(v time.Time) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldGTE(FieldMarkedAt, v))
}

// MarkedAtLT applies the LT predicate on the "marked_at" field.
func MarkedAtLT(v time.Time) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLT(FieldMarkedAt, v))
}

// MarkedAtLTE applies the LTE predicate on the "marked_at" field.
func MarkedAtLTE(v time.Time) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.FieldLTE(FieldMarkedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceHistoricalMark) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceHistoricalMark) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceHistoricalMark) predicate.InvoiceHistoricalMark {
	return predicate.InvoiceHistoricalMark(sql.NotPredicates(p))
}
